/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * trip id and name
 */
@JsonPropertyOrder({
  TripInfo.JSON_PROPERTY_TRIP_ID,
  TripInfo.JSON_PROPERTY_ROUTE_SHORT_NAME,
  TripInfo.JSON_PROPERTY_DISPLAY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class TripInfo {
  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nonnull
  private String tripId;

  public static final String JSON_PROPERTY_ROUTE_SHORT_NAME = "routeShortName";
  @jakarta.annotation.Nullable
  private String routeShortName;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @jakarta.annotation.Nullable
  private String displayName;

  public TripInfo() {
  }

  public TripInfo tripId(@jakarta.annotation.Nonnull String tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * trip ID (dataset trip id prefixed with the dataset tag)
   * @return tripId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripId(@jakarta.annotation.Nonnull String tripId) {
    this.tripId = tripId;
  }

  public TripInfo routeShortName(@jakarta.annotation.Nullable String routeShortName) {
    
    this.routeShortName = routeShortName;
    return this;
  }

  /**
   * trip display name (api version &lt; 4)
   * @return routeShortName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTE_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRouteShortName() {
    return routeShortName;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteShortName(@jakarta.annotation.Nullable String routeShortName) {
    this.routeShortName = routeShortName;
  }

  public TripInfo displayName(@jakarta.annotation.Nullable String displayName) {
    
    this.displayName = displayName;
    return this;
  }

  /**
   * trip display name (api version &gt;&#x3D; 4)
   * @return displayName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(@jakarta.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripInfo tripInfo = (TripInfo) o;
    return Objects.equals(this.tripId, tripInfo.tripId) &&
        Objects.equals(this.routeShortName, tripInfo.routeShortName) &&
        Objects.equals(this.displayName, tripInfo.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tripId, routeShortName, displayName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripInfo {\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    routeShortName: ").append(toIndentedString(routeShortName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

