/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.FareTransfer;
import dev.bileto.motis.client.model.Leg;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Itinerary
 */
class ItineraryTest {
    private final Itinerary model = new Itinerary();

    /**
     * Model tests for Itinerary
     */
    @Test
    void testItinerary() {
        // TODO: test Itinerary
    }

    /**
     * Test the property 'duration'
     */
    @Test
    void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'transfers'
     */
    @Test
    void transfersTest() {
        // TODO: test transfers
    }

    /**
     * Test the property 'legs'
     */
    @Test
    void legsTest() {
        // TODO: test legs
    }

    /**
     * Test the property 'fareTransfers'
     */
    @Test
    void fareTransfersTest() {
        // TODO: test fareTransfers
    }

}
