/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Area;
import dev.bileto.motis.client.model.LocationType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Match
 */
class MatchTest {
    private final Match model = new Match();

    /**
     * Model tests for Match
     */
    @Test
    void testMatch() {
        // TODO: test Match
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'tokens'
     */
    @Test
    void tokensTest() {
        // TODO: test tokens
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lat'
     */
    @Test
    void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'lon'
     */
    @Test
    void lonTest() {
        // TODO: test lon
    }

    /**
     * Test the property 'level'
     */
    @Test
    void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'street'
     */
    @Test
    void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'houseNumber'
     */
    @Test
    void houseNumberTest() {
        // TODO: test houseNumber
    }

    /**
     * Test the property 'zip'
     */
    @Test
    void zipTest() {
        // TODO: test zip
    }

    /**
     * Test the property 'tz'
     */
    @Test
    void tzTest() {
        // TODO: test tz
    }

    /**
     * Test the property 'areas'
     */
    @Test
    void areasTest() {
        // TODO: test areas
    }

    /**
     * Test the property 'score'
     */
    @Test
    void scoreTest() {
        // TODO: test score
    }

}
