/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Itinerary;
import dev.bileto.motis.client.model.Place;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Plan200Response
 */
class Plan200ResponseTest {
    private final Plan200Response model = new Plan200Response();

    /**
     * Model tests for Plan200Response
     */
    @Test
    void testPlan200Response() {
        // TODO: test Plan200Response
    }

    /**
     * Test the property 'requestParameters'
     */
    @Test
    void requestParametersTest() {
        // TODO: test requestParameters
    }

    /**
     * Test the property 'debugOutput'
     */
    @Test
    void debugOutputTest() {
        // TODO: test debugOutput
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'direct'
     */
    @Test
    void directTest() {
        // TODO: test direct
    }

    /**
     * Test the property 'itineraries'
     */
    @Test
    void itinerariesTest() {
        // TODO: test itineraries
    }

    /**
     * Test the property 'previousPageCursor'
     */
    @Test
    void previousPageCursorTest() {
        // TODO: test previousPageCursor
    }

    /**
     * Test the property 'nextPageCursor'
     */
    @Test
    void nextPageCursorTest() {
        // TODO: test nextPageCursor
    }

}
