/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Place;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReachablePlace
 */
class ReachablePlaceTest {
    private final ReachablePlace model = new ReachablePlace();

    /**
     * Model tests for ReachablePlace
     */
    @Test
    void testReachablePlace() {
        // TODO: test ReachablePlace
    }

    /**
     * Test the property 'place'
     */
    @Test
    void placeTest() {
        // TODO: test place
    }

    /**
     * Test the property 'duration'
     */
    @Test
    void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'k'
     */
    @Test
    void kTest() {
        // TODO: test k
    }

}
