/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Place;
import dev.bileto.motis.client.model.ReachablePlace;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Reachable
 */
class ReachableTest {
    private final Reachable model = new Reachable();

    /**
     * Model tests for Reachable
     */
    @Test
    void testReachable() {
        // TODO: test Reachable
    }

    /**
     * Test the property 'one'
     */
    @Test
    void oneTest() {
        // TODO: test one
    }

    /**
     * Test the property 'all'
     */
    @Test
    void allTest() {
        // TODO: test all
    }

}
