/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.RentalFormFactor;
import dev.bileto.motis.client.model.RentalPropulsionType;
import dev.bileto.motis.client.model.RentalReturnConstraint;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Rental
 */
class RentalTest {
    private final Rental model = new Rental();

    /**
     * Model tests for Rental
     */
    @Test
    void testRental() {
        // TODO: test Rental
    }

    /**
     * Test the property 'systemId'
     */
    @Test
    void systemIdTest() {
        // TODO: test systemId
    }

    /**
     * Test the property 'systemName'
     */
    @Test
    void systemNameTest() {
        // TODO: test systemName
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'stationName'
     */
    @Test
    void stationNameTest() {
        // TODO: test stationName
    }

    /**
     * Test the property 'fromStationName'
     */
    @Test
    void fromStationNameTest() {
        // TODO: test fromStationName
    }

    /**
     * Test the property 'toStationName'
     */
    @Test
    void toStationNameTest() {
        // TODO: test toStationName
    }

    /**
     * Test the property 'rentalUriAndroid'
     */
    @Test
    void rentalUriAndroidTest() {
        // TODO: test rentalUriAndroid
    }

    /**
     * Test the property 'rentalUriIOS'
     */
    @Test
    void rentalUriIOSTest() {
        // TODO: test rentalUriIOS
    }

    /**
     * Test the property 'rentalUriWeb'
     */
    @Test
    void rentalUriWebTest() {
        // TODO: test rentalUriWeb
    }

    /**
     * Test the property 'formFactor'
     */
    @Test
    void formFactorTest() {
        // TODO: test formFactor
    }

    /**
     * Test the property 'propulsionType'
     */
    @Test
    void propulsionTypeTest() {
        // TODO: test propulsionType
    }

    /**
     * Test the property 'returnConstraint'
     */
    @Test
    void returnConstraintTest() {
        // TODO: test returnConstraint
    }

}
