/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EncodedPolyline
 */
class EncodedPolylineTest {
    private final EncodedPolyline model = new EncodedPolyline();

    /**
     * Model tests for EncodedPolyline
     */
    @Test
    void testEncodedPolyline() {
        // TODO: test EncodedPolyline
    }

    /**
     * Test the property 'points'
     */
    @Test
    void pointsTest() {
        // TODO: test points
    }

    /**
     * Test the property 'precision'
     */
    @Test
    void precisionTest() {
        // TODO: test precision
    }

    /**
     * Test the property 'length'
     */
    @Test
    void lengthTest() {
        // TODO: test length
    }

}
