/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Initial200Response
 */
class Initial200ResponseTest {
    private final Initial200Response model = new Initial200Response();

    /**
     * Model tests for Initial200Response
     */
    @Test
    void testInitial200Response() {
        // TODO: test Initial200Response
    }

    /**
     * Test the property 'lat'
     */
    @Test
    void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property 'lon'
     */
    @Test
    void lonTest() {
        // TODO: test lon
    }

    /**
     * Test the property 'zoom'
     */
    @Test
    void zoomTest() {
        // TODO: test zoom
    }

}
