/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RentalReturnConstraint
 */
class RentalReturnConstraintTest {
    /**
     * Model tests for RentalReturnConstraint
     */
    @Test
    void testRentalReturnConstraint() {
        // TODO: test RentalReturnConstraint
    }

}
