/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.model;

import com.bileto.motis.client.model.Mode;
import com.bileto.motis.client.model.PickupDropoffType;
import com.bileto.motis.client.model.Place;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StopTime
 */
@Disabled
class StopTimeTest {
    private final StopTime model = new StopTime();

    /**
     * Model tests for StopTime
     */
    @Test
    void testStopTime() {
        // TODO: test StopTime
    }

    /**
     * Test the property 'place'
     */
    @Test
    void placeTest() {
        // TODO: test place
    }

    /**
     * Test the property 'mode'
     */
    @Test
    void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'realTime'
     */
    @Test
    void realTimeTest() {
        // TODO: test realTime
    }

    /**
     * Test the property 'headsign'
     */
    @Test
    void headsignTest() {
        // TODO: test headsign
    }

    /**
     * Test the property 'agencyId'
     */
    @Test
    void agencyIdTest() {
        // TODO: test agencyId
    }

    /**
     * Test the property 'agencyName'
     */
    @Test
    void agencyNameTest() {
        // TODO: test agencyName
    }

    /**
     * Test the property 'agencyUrl'
     */
    @Test
    void agencyUrlTest() {
        // TODO: test agencyUrl
    }

    /**
     * Test the property 'routeColor'
     */
    @Test
    void routeColorTest() {
        // TODO: test routeColor
    }

    /**
     * Test the property 'routeTextColor'
     */
    @Test
    void routeTextColorTest() {
        // TODO: test routeTextColor
    }

    /**
     * Test the property 'tripId'
     */
    @Test
    void tripIdTest() {
        // TODO: test tripId
    }

    /**
     * Test the property 'routeType'
     */
    @Test
    void routeTypeTest() {
        // TODO: test routeType
    }

    /**
     * Test the property 'routeShortName'
     */
    @Test
    void routeShortNameTest() {
        // TODO: test routeShortName
    }

    /**
     * Test the property 'routeLongName'
     */
    @Test
    void routeLongNameTest() {
        // TODO: test routeLongName
    }

    /**
     * Test the property 'tripShortName'
     */
    @Test
    void tripShortNameTest() {
        // TODO: test tripShortName
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'pickupDropoffType'
     */
    @Test
    void pickupDropoffTypeTest() {
        // TODO: test pickupDropoffType
    }

    /**
     * Test the property 'cancelled'
     */
    @Test
    void cancelledTest() {
        // TODO: test cancelled
    }

    /**
     * Test the property 'tripCancelled'
     */
    @Test
    void tripCancelledTest() {
        // TODO: test tripCancelled
    }

    /**
     * Test the property 'source'
     */
    @Test
    void sourceTest() {
        // TODO: test source
    }

}
