/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.model;

import com.bileto.motis.client.model.Mode;
import com.bileto.motis.client.model.Place;
import com.bileto.motis.client.model.TripInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TripSegment
 */
@Disabled
class TripSegmentTest {
    private final TripSegment model = new TripSegment();

    /**
     * Model tests for TripSegment
     */
    @Test
    void testTripSegment() {
        // TODO: test TripSegment
    }

    /**
     * Test the property 'trips'
     */
    @Test
    void tripsTest() {
        // TODO: test trips
    }

    /**
     * Test the property 'routeColor'
     */
    @Test
    void routeColorTest() {
        // TODO: test routeColor
    }

    /**
     * Test the property 'mode'
     */
    @Test
    void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'distance'
     */
    @Test
    void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'departure'
     */
    @Test
    void departureTest() {
        // TODO: test departure
    }

    /**
     * Test the property 'arrival'
     */
    @Test
    void arrivalTest() {
        // TODO: test arrival
    }

    /**
     * Test the property 'scheduledDeparture'
     */
    @Test
    void scheduledDepartureTest() {
        // TODO: test scheduledDeparture
    }

    /**
     * Test the property 'scheduledArrival'
     */
    @Test
    void scheduledArrivalTest() {
        // TODO: test scheduledArrival
    }

    /**
     * Test the property 'realTime'
     */
    @Test
    void realTimeTest() {
        // TODO: test realTime
    }

    /**
     * Test the property 'polyline'
     */
    @Test
    void polylineTest() {
        // TODO: test polyline
    }

}
