/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TripInfo
 */
class TripInfoTest {
    private final TripInfo model = new TripInfo();

    /**
     * Model tests for TripInfo
     */
    @Test
    void testTripInfo() {
        // TODO: test TripInfo
    }

    /**
     * Test the property 'tripId'
     */
    @Test
    void tripIdTest() {
        // TODO: test tripId
    }

    /**
     * Test the property 'routeShortName'
     */
    @Test
    void routeShortNameTest() {
        // TODO: test routeShortName
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    void displayNameTest() {
        // TODO: test displayName
    }

}
