/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bileto.motis.client.api;

import com.bileto.motis.client.model.Itinerary;
import com.bileto.motis.client.model.Mode;
import java.time.OffsetDateTime;
import com.bileto.motis.client.model.Stoptimes200Response;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for TimetableApi
 */
@Disabled
public class TimetableApiTest {

    private final TimetableApi api = new TimetableApi();

    
    /**
     * Get the next N departures or arrivals of a stop sorted by time
     *
     * 
     */
    @Test
    public void stoptimesTest()  {
        // uncomment below to test the function
        //String stopId = null;
        //Integer n = null;
        //OffsetDateTime time = null;
        //Boolean arriveBy = null;
        //String direction = null;
        //List<Mode> mode = null;
        //Integer radius = null;
        //Boolean exactRadius = null;
        //String pageCursor = null;
        //Boolean withScheduledSkippedStops = null;
        //String language = null;
        //Stoptimes200Response response = api.stoptimes(stopId, n, time, arriveBy, direction, mode, radius, exactRadius, pageCursor, withScheduledSkippedStops, language);

        // TODO: test validations
    }
    
    /**
     * Get a trip as itinerary
     *
     * 
     */
    @Test
    public void tripTest()  {
        // uncomment below to test the function
        //String tripId = null;
        //Boolean withScheduledSkippedStops = null;
        //Boolean joinInterlinedLegs = null;
        //String language = null;
        //Itinerary response = api.trip(tripId, withScheduledSkippedStops, joinInterlinedLegs, language);

        // TODO: test validations
    }
    
}
