/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.api;

import java.math.BigDecimal;
import dev.bileto.motis.client.model.LocationType;
import dev.bileto.motis.client.model.Match;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for GeocodeApi
 */
@Disabled
public class GeocodeApiTest {

    private final GeocodeApi api = new GeocodeApi();

    
    /**
     * Autocompletion &amp; geocoding that resolves user input addresses including coordinates
     *
     * 
     */
    @Test
    public void geocodeTest()  {
        // uncomment below to test the function
        //String text = null;
        //String language = null;
        //LocationType type = null;
        //String place = null;
        //BigDecimal placeBias = null;
        //List<Match> response = api.geocode(text, language, type, place, placeBias);

        // TODO: test validations
    }
    
    /**
     * Translate coordinates to the closest address(es)/places/stops.
     *
     * 
     */
    @Test
    public void reverseGeocodeTest()  {
        // uncomment below to test the function
        //String place = null;
        //LocationType type = null;
        //List<Match> response = api.reverseGeocode(place, type);

        // TODO: test validations
    }
    
}
