/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * The effect of this problem on the affected entity.
 */
public enum AlertEffect {
  
  NO_SERVICE("NO_SERVICE"),
  
  REDUCED_SERVICE("REDUCED_SERVICE"),
  
  SIGNIFICANT_DELAYS("SIGNIFICANT_DELAYS"),
  
  DETOUR("DETOUR"),
  
  ADDITIONAL_SERVICE("ADDITIONAL_SERVICE"),
  
  MODIFIED_SERVICE("MODIFIED_SERVICE"),
  
  OTHER_EFFECT("OTHER_EFFECT"),
  
  UNKNOWN_EFFECT("UNKNOWN_EFFECT"),
  
  STOP_MOVED("STOP_MOVED"),
  
  NO_EFFECT("NO_EFFECT"),
  
  ACCESSIBILITY_ISSUE("ACCESSIBILITY_ISSUE");

  private String value;

  AlertEffect(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static AlertEffect fromValue(String value) {
    for (AlertEffect b : AlertEffect.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

