/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.FareMedia;
import dev.bileto.motis.client.model.RiderCategory;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FareProduct
 */
@JsonPropertyOrder({
  FareProduct.JSON_PROPERTY_NAME,
  FareProduct.JSON_PROPERTY_AMOUNT,
  FareProduct.JSON_PROPERTY_CURRENCY,
  FareProduct.JSON_PROPERTY_RIDER_CATEGORY,
  FareProduct.JSON_PROPERTY_MEDIA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class FareProduct {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private BigDecimal amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_RIDER_CATEGORY = "riderCategory";
  @jakarta.annotation.Nullable
  private RiderCategory riderCategory;

  public static final String JSON_PROPERTY_MEDIA = "media";
  @jakarta.annotation.Nullable
  private FareMedia media;

  public FareProduct() {
  }

  public FareProduct name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the fare product as displayed to riders.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public FareProduct amount(@jakarta.annotation.Nonnull BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * The cost of the fare product. May be negative to represent transfer discounts. May be zero to represent a fare product that is free.
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull BigDecimal amount) {
    this.amount = amount;
  }

  public FareProduct currency(@jakarta.annotation.Nonnull String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * ISO 4217 currency code. The currency of the cost of the fare product.
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }

  public FareProduct riderCategory(@jakarta.annotation.Nullable RiderCategory riderCategory) {
    
    this.riderCategory = riderCategory;
    return this;
  }

  /**
   * Get riderCategory
   * @return riderCategory
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RIDER_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RiderCategory getRiderCategory() {
    return riderCategory;
  }


  @JsonProperty(value = JSON_PROPERTY_RIDER_CATEGORY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRiderCategory(@jakarta.annotation.Nullable RiderCategory riderCategory) {
    this.riderCategory = riderCategory;
  }

  public FareProduct media(@jakarta.annotation.Nullable FareMedia media) {
    
    this.media = media;
    return this;
  }

  /**
   * Get media
   * @return media
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEDIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FareMedia getMedia() {
    return media;
  }


  @JsonProperty(value = JSON_PROPERTY_MEDIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedia(@jakarta.annotation.Nullable FareMedia media) {
    this.media = media;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FareProduct fareProduct = (FareProduct) o;
    return Objects.equals(this.name, fareProduct.name) &&
        Objects.equals(this.amount, fareProduct.amount) &&
        Objects.equals(this.currency, fareProduct.currency) &&
        Objects.equals(this.riderCategory, fareProduct.riderCategory) &&
        Objects.equals(this.media, fareProduct.media);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, amount, currency, riderCategory, media);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FareProduct {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    riderCategory: ").append(toIndentedString(riderCategory)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

