/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.FareMediaType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FareMedia
 */
@JsonPropertyOrder({
  FareMedia.JSON_PROPERTY_FARE_MEDIA_NAME,
  FareMedia.JSON_PROPERTY_FARE_MEDIA_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class FareMedia {
  public static final String JSON_PROPERTY_FARE_MEDIA_NAME = "fareMediaName";
  @jakarta.annotation.Nullable
  private String fareMediaName;

  public static final String JSON_PROPERTY_FARE_MEDIA_TYPE = "fareMediaType";
  @jakarta.annotation.Nonnull
  private FareMediaType fareMediaType;

  public FareMedia() {
  }

  public FareMedia fareMediaName(@jakarta.annotation.Nullable String fareMediaName) {
    
    this.fareMediaName = fareMediaName;
    return this;
  }

  /**
   * Name of the fare media. Required for transit cards and mobile apps.
   * @return fareMediaName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFareMediaName() {
    return fareMediaName;
  }


  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFareMediaName(@jakarta.annotation.Nullable String fareMediaName) {
    this.fareMediaName = fareMediaName;
  }

  public FareMedia fareMediaType(@jakarta.annotation.Nonnull FareMediaType fareMediaType) {
    
    this.fareMediaType = fareMediaType;
    return this;
  }

  /**
   * The type of fare media.
   * @return fareMediaType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FareMediaType getFareMediaType() {
    return fareMediaType;
  }


  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFareMediaType(@jakarta.annotation.Nonnull FareMediaType fareMediaType) {
    this.fareMediaType = fareMediaType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FareMedia fareMedia = (FareMedia) o;
    return Objects.equals(this.fareMediaName, fareMedia.fareMediaName) &&
        Objects.equals(this.fareMediaType, fareMedia.fareMediaType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fareMediaName, fareMediaType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FareMedia {\n");
    sb.append("    fareMediaName: ").append(toIndentedString(fareMediaName)).append("\n");
    sb.append("    fareMediaType: ").append(toIndentedString(fareMediaType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

