/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.FareMediaType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FareMedia
 */
@JsonPropertyOrder({
  FareMedia.JSON_PROPERTY_FARE_MEDIA_NAME,
  FareMedia.JSON_PROPERTY_FARE_MEDIA_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class FareMedia {
  public static final String JSON_PROPERTY_FARE_MEDIA_NAME = "fareMediaName";
  @jakarta.annotation.Nullable
  private String fareMediaName;

  public static final String JSON_PROPERTY_FARE_MEDIA_TYPE = "fareMediaType";
  @jakarta.annotation.Nonnull
  private FareMediaType fareMediaType;

  public FareMedia() {
  }

  public FareMedia fareMediaName(@jakarta.annotation.Nullable String fareMediaName) {
    
    this.fareMediaName = fareMediaName;
    return this;
  }

  /**
   * Name of the fare media. Required for transit cards and mobile apps.
   * @return fareMediaName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFareMediaName() {
    return fareMediaName;
  }


  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFareMediaName(@jakarta.annotation.Nullable String fareMediaName) {
    this.fareMediaName = fareMediaName;
  }

  public FareMedia fareMediaType(@jakarta.annotation.Nonnull FareMediaType fareMediaType) {
    
    this.fareMediaType = fareMediaType;
    return this;
  }

  /**
   * The type of fare media.
   * @return fareMediaType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FareMediaType getFareMediaType() {
    return fareMediaType;
  }


  @JsonProperty(value = JSON_PROPERTY_FARE_MEDIA_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFareMediaType(@jakarta.annotation.Nonnull FareMediaType fareMediaType) {
    this.fareMediaType = fareMediaType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FareMedia fareMedia = (FareMedia) o;
    return Objects.equals(this.fareMediaName, fareMedia.fareMediaName) &&
        Objects.equals(this.fareMediaType, fareMedia.fareMediaType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fareMediaName, fareMediaType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FareMedia {\n");
    sb.append("    fareMediaName: ").append(toIndentedString(fareMediaName)).append("\n");
    sb.append("    fareMediaType: ").append(toIndentedString(fareMediaType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

