/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * - &#x60;NONE&#x60;: No fare media involved (e.g., cash payment) - &#x60;PAPER_TICKET&#x60;: Physical paper ticket - &#x60;TRANSIT_CARD&#x60;: Physical transit card with stored value - &#x60;CONTACTLESS_EMV&#x60;: cEMV (contactless payment) - &#x60;MOBILE_APP&#x60;: Mobile app with virtual transit cards/passes 
 */
public enum FareMediaType {
  
  NONE("NONE"),
  
  PAPER_TICKET("PAPER_TICKET"),
  
  TRANSIT_CARD("TRANSIT_CARD"),
  
  CONTACTLESS_EMV("CONTACTLESS_EMV"),
  
  MOBILE_APP("MOBILE_APP");

  private String value;

  FareMediaType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static FareMediaType fromValue(String value) {
    for (FareMediaType b : FareMediaType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

