/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Mode;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LegId
 */
@JsonPropertyOrder({
  LegId.JSON_PROPERTY_DISPLAY_NAME,
  LegId.JSON_PROPERTY_TRIP_ID,
  LegId.JSON_PROPERTY_FROM_ID,
  LegId.JSON_PROPERTY_FROM_LAT,
  LegId.JSON_PROPERTY_FROM_LON,
  LegId.JSON_PROPERTY_FROM_LEVEL,
  LegId.JSON_PROPERTY_TO_ID,
  LegId.JSON_PROPERTY_TO_LAT,
  LegId.JSON_PROPERTY_TO_LON,
  LegId.JSON_PROPERTY_TO_LEVEL,
  LegId.JSON_PROPERTY_SCHED_START,
  LegId.JSON_PROPERTY_SCHED_END,
  LegId.JSON_PROPERTY_MODE,
  LegId.JSON_PROPERTY_SCHEDULED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class LegId {
  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @jakarta.annotation.Nonnull
  private String displayName;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nonnull
  private String tripId;

  public static final String JSON_PROPERTY_FROM_ID = "fromId";
  @jakarta.annotation.Nonnull
  private String fromId;

  public static final String JSON_PROPERTY_FROM_LAT = "fromLat";
  @jakarta.annotation.Nonnull
  private Double fromLat;

  public static final String JSON_PROPERTY_FROM_LON = "fromLon";
  @jakarta.annotation.Nonnull
  private Double fromLon;

  public static final String JSON_PROPERTY_FROM_LEVEL = "fromLevel";
  @jakarta.annotation.Nullable
  private Double fromLevel;

  public static final String JSON_PROPERTY_TO_ID = "toId";
  @jakarta.annotation.Nonnull
  private String toId;

  public static final String JSON_PROPERTY_TO_LAT = "toLat";
  @jakarta.annotation.Nonnull
  private Double toLat;

  public static final String JSON_PROPERTY_TO_LON = "toLon";
  @jakarta.annotation.Nonnull
  private Double toLon;

  public static final String JSON_PROPERTY_TO_LEVEL = "toLevel";
  @jakarta.annotation.Nullable
  private Double toLevel;

  public static final String JSON_PROPERTY_SCHED_START = "schedStart";
  @jakarta.annotation.Nonnull
  private Long schedStart;

  public static final String JSON_PROPERTY_SCHED_END = "schedEnd";
  @jakarta.annotation.Nonnull
  private Long schedEnd;

  public static final String JSON_PROPERTY_MODE = "mode";
  @jakarta.annotation.Nonnull
  private Mode mode;

  public static final String JSON_PROPERTY_SCHEDULED = "scheduled";
  @jakarta.annotation.Nonnull
  private Boolean scheduled;

  public LegId() {
  }

  public LegId displayName(@jakarta.annotation.Nonnull String displayName) {
    
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(value = JSON_PROPERTY_DISPLAY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(@jakarta.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }

  public LegId tripId(@jakarta.annotation.Nonnull String tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRIP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTripId() {
    return tripId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIP_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripId(@jakarta.annotation.Nonnull String tripId) {
    this.tripId = tripId;
  }

  public LegId fromId(@jakarta.annotation.Nonnull String fromId) {
    
    this.fromId = fromId;
    return this;
  }

  /**
   * from stop stopId
   * @return fromId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFromId() {
    return fromId;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromId(@jakarta.annotation.Nonnull String fromId) {
    this.fromId = fromId;
  }

  public LegId fromLat(@jakarta.annotation.Nonnull Double fromLat) {
    
    this.fromLat = fromLat;
    return this;
  }

  /**
   * latitude of the leg&#39;s from endpoint
   * @return fromLat
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getFromLat() {
    return fromLat;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromLat(@jakarta.annotation.Nonnull Double fromLat) {
    this.fromLat = fromLat;
  }

  public LegId fromLon(@jakarta.annotation.Nonnull Double fromLon) {
    
    this.fromLon = fromLon;
    return this;
  }

  /**
   * longitude of the leg&#39;s from endpoint
   * @return fromLon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FROM_LON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getFromLon() {
    return fromLon;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_LON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromLon(@jakarta.annotation.Nonnull Double fromLon) {
    this.fromLon = fromLon;
  }

  public LegId fromLevel(@jakarta.annotation.Nullable Double fromLevel) {
    
    this.fromLevel = fromLevel;
    return this;
  }

  /**
   * Optional level (floor) of the leg&#39;s from endpoint for indoor routing.
   * @return fromLevel
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getFromLevel() {
    return fromLevel;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromLevel(@jakarta.annotation.Nullable Double fromLevel) {
    this.fromLevel = fromLevel;
  }

  public LegId toId(@jakarta.annotation.Nonnull String toId) {
    
    this.toId = toId;
    return this;
  }

  /**
   * to stop stopId
   * @return toId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToId() {
    return toId;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToId(@jakarta.annotation.Nonnull String toId) {
    this.toId = toId;
  }

  public LegId toLat(@jakarta.annotation.Nonnull Double toLat) {
    
    this.toLat = toLat;
    return this;
  }

  /**
   * latitude of the leg&#39;s to endpoint
   * @return toLat
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getToLat() {
    return toLat;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_LAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToLat(@jakarta.annotation.Nonnull Double toLat) {
    this.toLat = toLat;
  }

  public LegId toLon(@jakarta.annotation.Nonnull Double toLon) {
    
    this.toLon = toLon;
    return this;
  }

  /**
   * longitude of the leg&#39;s to endpoint
   * @return toLon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO_LON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getToLon() {
    return toLon;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_LON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToLon(@jakarta.annotation.Nonnull Double toLon) {
    this.toLon = toLon;
  }

  public LegId toLevel(@jakarta.annotation.Nullable Double toLevel) {
    
    this.toLevel = toLevel;
    return this;
  }

  /**
   * Optional level (floor) of the leg&#39;s to endpoint for indoor routing.
   * @return toLevel
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getToLevel() {
    return toLevel;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToLevel(@jakarta.annotation.Nullable Double toLevel) {
    this.toLevel = toLevel;
  }

  public LegId schedStart(@jakarta.annotation.Nonnull Long schedStart) {
    
    this.schedStart = schedStart;
    return this;
  }

  /**
   * Scheduled departure time as a Unix timestamp in seconds.
   * @return schedStart
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCHED_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSchedStart() {
    return schedStart;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHED_START, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSchedStart(@jakarta.annotation.Nonnull Long schedStart) {
    this.schedStart = schedStart;
  }

  public LegId schedEnd(@jakarta.annotation.Nonnull Long schedEnd) {
    
    this.schedEnd = schedEnd;
    return this;
  }

  /**
   * Scheduled arrival time as a Unix timestamp in seconds.
   * @return schedEnd
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCHED_END, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSchedEnd() {
    return schedEnd;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHED_END, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSchedEnd(@jakarta.annotation.Nonnull Long schedEnd) {
    this.schedEnd = schedEnd;
  }

  public LegId mode(@jakarta.annotation.Nonnull Mode mode) {
    
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Mode getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMode(@jakarta.annotation.Nonnull Mode mode) {
    this.mode = mode;
  }

  public LegId scheduled(@jakarta.annotation.Nonnull Boolean scheduled) {
    
    this.scheduled = scheduled;
    return this;
  }

  /**
   * Get scheduled
   * @return scheduled
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCHEDULED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getScheduled() {
    return scheduled;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScheduled(@jakarta.annotation.Nonnull Boolean scheduled) {
    this.scheduled = scheduled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegId legId = (LegId) o;
    return Objects.equals(this.displayName, legId.displayName) &&
        Objects.equals(this.tripId, legId.tripId) &&
        Objects.equals(this.fromId, legId.fromId) &&
        Objects.equals(this.fromLat, legId.fromLat) &&
        Objects.equals(this.fromLon, legId.fromLon) &&
        Objects.equals(this.fromLevel, legId.fromLevel) &&
        Objects.equals(this.toId, legId.toId) &&
        Objects.equals(this.toLat, legId.toLat) &&
        Objects.equals(this.toLon, legId.toLon) &&
        Objects.equals(this.toLevel, legId.toLevel) &&
        Objects.equals(this.schedStart, legId.schedStart) &&
        Objects.equals(this.schedEnd, legId.schedEnd) &&
        Objects.equals(this.mode, legId.mode) &&
        Objects.equals(this.scheduled, legId.scheduled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, tripId, fromId, fromLat, fromLon, fromLevel, toId, toLat, toLon, toLevel, schedStart, schedEnd, mode, scheduled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegId {\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    fromId: ").append(toIndentedString(fromId)).append("\n");
    sb.append("    fromLat: ").append(toIndentedString(fromLat)).append("\n");
    sb.append("    fromLon: ").append(toIndentedString(fromLon)).append("\n");
    sb.append("    fromLevel: ").append(toIndentedString(fromLevel)).append("\n");
    sb.append("    toId: ").append(toIndentedString(toId)).append("\n");
    sb.append("    toLat: ").append(toIndentedString(toLat)).append("\n");
    sb.append("    toLon: ").append(toIndentedString(toLon)).append("\n");
    sb.append("    toLevel: ").append(toIndentedString(toLevel)).append("\n");
    sb.append("    schedStart: ").append(toIndentedString(schedStart)).append("\n");
    sb.append("    schedEnd: ").append(toIndentedString(schedEnd)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    scheduled: ").append(toIndentedString(scheduled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

