/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Area;
import dev.bileto.motis.client.model.LocationType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GeoCoding match
 */
@JsonPropertyOrder({
  Match.JSON_PROPERTY_TYPE,
  Match.JSON_PROPERTY_TOKENS,
  Match.JSON_PROPERTY_NAME,
  Match.JSON_PROPERTY_ID,
  Match.JSON_PROPERTY_LAT,
  Match.JSON_PROPERTY_LON,
  Match.JSON_PROPERTY_LEVEL,
  Match.JSON_PROPERTY_STREET,
  Match.JSON_PROPERTY_HOUSE_NUMBER,
  Match.JSON_PROPERTY_ZIP,
  Match.JSON_PROPERTY_TZ,
  Match.JSON_PROPERTY_AREAS,
  Match.JSON_PROPERTY_SCORE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.15.0")
public class Match {
  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private LocationType type;

  public static final String JSON_PROPERTY_TOKENS = "tokens";
  @jakarta.annotation.Nonnull
  private List<List<BigDecimal>> tokens = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_LAT = "lat";
  @jakarta.annotation.Nonnull
  private BigDecimal lat;

  public static final String JSON_PROPERTY_LON = "lon";
  @jakarta.annotation.Nonnull
  private BigDecimal lon;

  public static final String JSON_PROPERTY_LEVEL = "level";
  @jakarta.annotation.Nullable
  private BigDecimal level;

  public static final String JSON_PROPERTY_STREET = "street";
  @jakarta.annotation.Nullable
  private String street;

  public static final String JSON_PROPERTY_HOUSE_NUMBER = "houseNumber";
  @jakarta.annotation.Nullable
  private String houseNumber;

  public static final String JSON_PROPERTY_ZIP = "zip";
  @jakarta.annotation.Nullable
  private String zip;

  public static final String JSON_PROPERTY_TZ = "tz";
  @jakarta.annotation.Nullable
  private String tz;

  public static final String JSON_PROPERTY_AREAS = "areas";
  @jakarta.annotation.Nonnull
  private List<Area> areas = new ArrayList<>();

  public static final String JSON_PROPERTY_SCORE = "score";
  @jakarta.annotation.Nonnull
  private BigDecimal score;

  public Match() {
  }

  public Match type(@jakarta.annotation.Nonnull LocationType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocationType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull LocationType type) {
    this.type = type;
  }

  public Match tokens(@jakarta.annotation.Nonnull List<List<BigDecimal>> tokens) {
    
    this.tokens = tokens;
    return this;
  }

  public Match addTokensItem(List<BigDecimal> tokensItem) {
    if (this.tokens == null) {
      this.tokens = new ArrayList<>();
    }
    this.tokens.add(tokensItem);
    return this;
  }

  /**
   * list of non-overlapping tokens that were matched
   * @return tokens
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOKENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<List<BigDecimal>> getTokens() {
    return tokens;
  }


  @JsonProperty(JSON_PROPERTY_TOKENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokens(@jakarta.annotation.Nonnull List<List<BigDecimal>> tokens) {
    this.tokens = tokens;
  }

  public Match name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * name of the location (transit stop / PoI / address)
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }

  public Match id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * unique ID of the location
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public Match lat(@jakarta.annotation.Nonnull BigDecimal lat) {
    
    this.lat = lat;
    return this;
  }

  /**
   * latitude
   * @return lat
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getLat() {
    return lat;
  }


  @JsonProperty(JSON_PROPERTY_LAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLat(@jakarta.annotation.Nonnull BigDecimal lat) {
    this.lat = lat;
  }

  public Match lon(@jakarta.annotation.Nonnull BigDecimal lon) {
    
    this.lon = lon;
    return this;
  }

  /**
   * longitude
   * @return lon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getLon() {
    return lon;
  }


  @JsonProperty(JSON_PROPERTY_LON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLon(@jakarta.annotation.Nonnull BigDecimal lon) {
    this.lon = lon;
  }

  public Match level(@jakarta.annotation.Nullable BigDecimal level) {
    
    this.level = level;
    return this;
  }

  /**
   * level according to OpenStreetMap (at the moment only for public transport) 
   * @return level
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLevel() {
    return level;
  }


  @JsonProperty(JSON_PROPERTY_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel(@jakarta.annotation.Nullable BigDecimal level) {
    this.level = level;
  }

  public Match street(@jakarta.annotation.Nullable String street) {
    
    this.street = street;
    return this;
  }

  /**
   * street name
   * @return street
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreet() {
    return street;
  }


  @JsonProperty(JSON_PROPERTY_STREET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreet(@jakarta.annotation.Nullable String street) {
    this.street = street;
  }

  public Match houseNumber(@jakarta.annotation.Nullable String houseNumber) {
    
    this.houseNumber = houseNumber;
    return this;
  }

  /**
   * house number
   * @return houseNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOUSE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHouseNumber() {
    return houseNumber;
  }


  @JsonProperty(JSON_PROPERTY_HOUSE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHouseNumber(@jakarta.annotation.Nullable String houseNumber) {
    this.houseNumber = houseNumber;
  }

  public Match zip(@jakarta.annotation.Nullable String zip) {
    
    this.zip = zip;
    return this;
  }

  /**
   * zip code
   * @return zip
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZip() {
    return zip;
  }


  @JsonProperty(JSON_PROPERTY_ZIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZip(@jakarta.annotation.Nullable String zip) {
    this.zip = zip;
  }

  public Match tz(@jakarta.annotation.Nullable String tz) {
    
    this.tz = tz;
    return this;
  }

  /**
   * timezone name (e.g. \&quot;Europe/Berlin\&quot;)
   * @return tz
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTz() {
    return tz;
  }


  @JsonProperty(JSON_PROPERTY_TZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTz(@jakarta.annotation.Nullable String tz) {
    this.tz = tz;
  }

  public Match areas(@jakarta.annotation.Nonnull List<Area> areas) {
    
    this.areas = areas;
    return this;
  }

  public Match addAreasItem(Area areasItem) {
    if (this.areas == null) {
      this.areas = new ArrayList<>();
    }
    this.areas.add(areasItem);
    return this;
  }

  /**
   * list of areas
   * @return areas
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AREAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Area> getAreas() {
    return areas;
  }


  @JsonProperty(JSON_PROPERTY_AREAS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAreas(@jakarta.annotation.Nonnull List<Area> areas) {
    this.areas = areas;
  }

  public Match score(@jakarta.annotation.Nonnull BigDecimal score) {
    
    this.score = score;
    return this;
  }

  /**
   * score according to the internal scoring system (the scoring algorithm might change in the future)
   * @return score
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getScore() {
    return score;
  }


  @JsonProperty(JSON_PROPERTY_SCORE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScore(@jakarta.annotation.Nonnull BigDecimal score) {
    this.score = score;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Match match = (Match) o;
    return Objects.equals(this.type, match.type) &&
        Objects.equals(this.tokens, match.tokens) &&
        Objects.equals(this.name, match.name) &&
        Objects.equals(this.id, match.id) &&
        Objects.equals(this.lat, match.lat) &&
        Objects.equals(this.lon, match.lon) &&
        Objects.equals(this.level, match.level) &&
        Objects.equals(this.street, match.street) &&
        Objects.equals(this.houseNumber, match.houseNumber) &&
        Objects.equals(this.zip, match.zip) &&
        Objects.equals(this.tz, match.tz) &&
        Objects.equals(this.areas, match.areas) &&
        Objects.equals(this.score, match.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, tokens, name, id, lat, lon, level, street, houseNumber, zip, tz, areas, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Match {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    tz: ").append(toIndentedString(tz)).append("\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

