/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.ElevationCosts;
import dev.bileto.motis.client.model.Mode;
import dev.bileto.motis.client.model.PedestrianProfile;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OneToManyIntermodalParams
 */
@JsonPropertyOrder({
  OneToManyIntermodalParams.JSON_PROPERTY_ONE,
  OneToManyIntermodalParams.JSON_PROPERTY_MANY,
  OneToManyIntermodalParams.JSON_PROPERTY_TIME,
  OneToManyIntermodalParams.JSON_PROPERTY_MAX_TRAVEL_TIME,
  OneToManyIntermodalParams.JSON_PROPERTY_MAX_MATCHING_DISTANCE,
  OneToManyIntermodalParams.JSON_PROPERTY_ARRIVE_BY,
  OneToManyIntermodalParams.JSON_PROPERTY_MAX_TRANSFERS,
  OneToManyIntermodalParams.JSON_PROPERTY_MIN_TRANSFER_TIME,
  OneToManyIntermodalParams.JSON_PROPERTY_ADDITIONAL_TRANSFER_TIME,
  OneToManyIntermodalParams.JSON_PROPERTY_TRANSFER_TIME_FACTOR,
  OneToManyIntermodalParams.JSON_PROPERTY_USE_ROUTED_TRANSFERS,
  OneToManyIntermodalParams.JSON_PROPERTY_PEDESTRIAN_PROFILE,
  OneToManyIntermodalParams.JSON_PROPERTY_PEDESTRIAN_SPEED,
  OneToManyIntermodalParams.JSON_PROPERTY_CYCLING_SPEED,
  OneToManyIntermodalParams.JSON_PROPERTY_ELEVATION_COSTS,
  OneToManyIntermodalParams.JSON_PROPERTY_TRANSIT_MODES,
  OneToManyIntermodalParams.JSON_PROPERTY_PRE_TRANSIT_MODES,
  OneToManyIntermodalParams.JSON_PROPERTY_POST_TRANSIT_MODES,
  OneToManyIntermodalParams.JSON_PROPERTY_DIRECT_MODE,
  OneToManyIntermodalParams.JSON_PROPERTY_MAX_PRE_TRANSIT_TIME,
  OneToManyIntermodalParams.JSON_PROPERTY_MAX_POST_TRANSIT_TIME,
  OneToManyIntermodalParams.JSON_PROPERTY_MAX_DIRECT_TIME,
  OneToManyIntermodalParams.JSON_PROPERTY_WITH_DISTANCE,
  OneToManyIntermodalParams.JSON_PROPERTY_REQUIRE_BIKE_TRANSPORT,
  OneToManyIntermodalParams.JSON_PROPERTY_REQUIRE_CAR_TRANSPORT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class OneToManyIntermodalParams {
  public static final String JSON_PROPERTY_ONE = "one";
  @jakarta.annotation.Nonnull
  private String one;

  public static final String JSON_PROPERTY_MANY = "many";
  @jakarta.annotation.Nonnull
  private List<String> many = new ArrayList<>();

  public static final String JSON_PROPERTY_TIME = "time";
  @jakarta.annotation.Nullable
  private OffsetDateTime time;

  public static final String JSON_PROPERTY_MAX_TRAVEL_TIME = "maxTravelTime";
  @jakarta.annotation.Nullable
  private Integer maxTravelTime;

  public static final String JSON_PROPERTY_MAX_MATCHING_DISTANCE = "maxMatchingDistance";
  @jakarta.annotation.Nullable
  private BigDecimal maxMatchingDistance = new BigDecimal("25");

  public static final String JSON_PROPERTY_ARRIVE_BY = "arriveBy";
  @jakarta.annotation.Nullable
  private Boolean arriveBy = false;

  public static final String JSON_PROPERTY_MAX_TRANSFERS = "maxTransfers";
  @jakarta.annotation.Nullable
  private Integer maxTransfers;

  public static final String JSON_PROPERTY_MIN_TRANSFER_TIME = "minTransferTime";
  @jakarta.annotation.Nullable
  private Integer minTransferTime = 0;

  public static final String JSON_PROPERTY_ADDITIONAL_TRANSFER_TIME = "additionalTransferTime";
  @jakarta.annotation.Nullable
  private Integer additionalTransferTime = 0;

  public static final String JSON_PROPERTY_TRANSFER_TIME_FACTOR = "transferTimeFactor";
  @jakarta.annotation.Nullable
  private BigDecimal transferTimeFactor = new BigDecimal("1.0");

  public static final String JSON_PROPERTY_USE_ROUTED_TRANSFERS = "useRoutedTransfers";
  @jakarta.annotation.Nullable
  private Boolean useRoutedTransfers = false;

  public static final String JSON_PROPERTY_PEDESTRIAN_PROFILE = "pedestrianProfile";
  @jakarta.annotation.Nullable
  private PedestrianProfile pedestrianProfile = PedestrianProfile.FOOT;

  public static final String JSON_PROPERTY_PEDESTRIAN_SPEED = "pedestrianSpeed";
  @jakarta.annotation.Nullable
  private BigDecimal pedestrianSpeed;

  public static final String JSON_PROPERTY_CYCLING_SPEED = "cyclingSpeed";
  @jakarta.annotation.Nullable
  private BigDecimal cyclingSpeed;

  public static final String JSON_PROPERTY_ELEVATION_COSTS = "elevationCosts";
  @jakarta.annotation.Nullable
  private ElevationCosts elevationCosts = ElevationCosts.NONE;

  public static final String JSON_PROPERTY_TRANSIT_MODES = "transitModes";
  @jakarta.annotation.Nullable
  private List<Mode> transitModes = new ArrayList<>(Arrays.asList(Mode.TRANSIT));

  public static final String JSON_PROPERTY_PRE_TRANSIT_MODES = "preTransitModes";
  @jakarta.annotation.Nullable
  private List<Mode> preTransitModes = new ArrayList<>(Arrays.asList(Mode.WALK));

  public static final String JSON_PROPERTY_POST_TRANSIT_MODES = "postTransitModes";
  @jakarta.annotation.Nullable
  private List<Mode> postTransitModes = new ArrayList<>(Arrays.asList(Mode.WALK));

  public static final String JSON_PROPERTY_DIRECT_MODE = "directMode";
  @jakarta.annotation.Nullable
  private Mode directMode = Mode.WALK;

  public static final String JSON_PROPERTY_MAX_PRE_TRANSIT_TIME = "maxPreTransitTime";
  @jakarta.annotation.Nullable
  private Integer maxPreTransitTime = 900;

  public static final String JSON_PROPERTY_MAX_POST_TRANSIT_TIME = "maxPostTransitTime";
  @jakarta.annotation.Nullable
  private Integer maxPostTransitTime = 900;

  public static final String JSON_PROPERTY_MAX_DIRECT_TIME = "maxDirectTime";
  @jakarta.annotation.Nullable
  private Integer maxDirectTime = 1800;

  public static final String JSON_PROPERTY_WITH_DISTANCE = "withDistance";
  @jakarta.annotation.Nullable
  private Boolean withDistance = false;

  public static final String JSON_PROPERTY_REQUIRE_BIKE_TRANSPORT = "requireBikeTransport";
  @jakarta.annotation.Nullable
  private Boolean requireBikeTransport = false;

  public static final String JSON_PROPERTY_REQUIRE_CAR_TRANSPORT = "requireCarTransport";
  @jakarta.annotation.Nullable
  private Boolean requireCarTransport = false;

  public OneToManyIntermodalParams() {
  }

  public OneToManyIntermodalParams one(@jakarta.annotation.Nonnull String one) {
    
    this.one = one;
    return this;
  }

  /**
   * \\&#x60;latitude,longitude[,level]\\&#x60; tuple with - latitude and longitude in degrees - (optional) level: the OSM level (default: 0)  OR  stop id 
   * @return one
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ONE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOne() {
    return one;
  }


  @JsonProperty(value = JSON_PROPERTY_ONE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOne(@jakarta.annotation.Nonnull String one) {
    this.one = one;
  }

  public OneToManyIntermodalParams many(@jakarta.annotation.Nonnull List<String> many) {
    
    this.many = many;
    return this;
  }

  public OneToManyIntermodalParams addManyItem(String manyItem) {
    if (this.many == null) {
      this.many = new ArrayList<>();
    }
    this.many.add(manyItem);
    return this;
  }

  /**
   * array of:  \\&#x60;latitude,longitude[,level]\\&#x60; tuple with - latitude and longitude in degrees - (optional) level: the OSM level (default: 0)  OR  stop id  The number of accepted locations is limited by server config variable &#x60;onetomany_max_many&#x60;. 
   * @return many
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MANY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMany() {
    return many;
  }


  @JsonProperty(value = JSON_PROPERTY_MANY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMany(@jakarta.annotation.Nonnull List<String> many) {
    this.many = many;
  }

  public OneToManyIntermodalParams time(@jakarta.annotation.Nullable OffsetDateTime time) {
    
    this.time = time;
    return this;
  }

  /**
   * Optional. Defaults to the current time.  Departure time ($arriveBy&#x3D;false) / arrival date ($arriveBy&#x3D;true), 
   * @return time
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTime() {
    return time;
  }


  @JsonProperty(value = JSON_PROPERTY_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(@jakarta.annotation.Nullable OffsetDateTime time) {
    this.time = time;
  }

  public OneToManyIntermodalParams maxTravelTime(@jakarta.annotation.Nullable Integer maxTravelTime) {
    
    this.maxTravelTime = maxTravelTime;
    return this;
  }

  /**
   * The maximum travel time in minutes. If not provided, the routing uses the value hardcoded in the server which is usually quite high.  *Warning*: Use with care. Setting this too low can lead to optimal (e.g. the least transfers) journeys not being found. If this value is too low to reach the destination at all, it can lead to slow routing performance. 
   * @return maxTravelTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_TRAVEL_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxTravelTime() {
    return maxTravelTime;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_TRAVEL_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxTravelTime(@jakarta.annotation.Nullable Integer maxTravelTime) {
    this.maxTravelTime = maxTravelTime;
  }

  public OneToManyIntermodalParams maxMatchingDistance(@jakarta.annotation.Nullable BigDecimal maxMatchingDistance) {
    
    this.maxMatchingDistance = maxMatchingDistance;
    return this;
  }

  /**
   * maximum matching distance in meters to match geo coordinates to the street network
   * @return maxMatchingDistance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_MATCHING_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getMaxMatchingDistance() {
    return maxMatchingDistance;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_MATCHING_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxMatchingDistance(@jakarta.annotation.Nullable BigDecimal maxMatchingDistance) {
    this.maxMatchingDistance = maxMatchingDistance;
  }

  public OneToManyIntermodalParams arriveBy(@jakarta.annotation.Nullable Boolean arriveBy) {
    
    this.arriveBy = arriveBy;
    return this;
  }

  /**
   * Optional. Defaults to false, i.e. one to many search  true &#x3D; many to one false &#x3D; one to many 
   * @return arriveBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARRIVE_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getArriveBy() {
    return arriveBy;
  }


  @JsonProperty(value = JSON_PROPERTY_ARRIVE_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArriveBy(@jakarta.annotation.Nullable Boolean arriveBy) {
    this.arriveBy = arriveBy;
  }

  public OneToManyIntermodalParams maxTransfers(@jakarta.annotation.Nullable Integer maxTransfers) {
    
    this.maxTransfers = maxTransfers;
    return this;
  }

  /**
   * The maximum number of allowed transfers (i.e. interchanges between transit legs, pre- and postTransit do not count as transfers). &#x60;maxTransfers&#x3D;0&#x60; searches for direct transit connections without any transfers. If you want to search only for non-transit connections (&#x60;FOOT&#x60;, &#x60;CAR&#x60;, etc.), send an empty &#x60;transitModes&#x60; parameter instead.  If not provided, the routing uses the server-side default value which is hardcoded and very high to cover all use cases.  *Warning*: Use with care. Setting this too low can lead to optimal (e.g. the fastest) journeys not being found. If this value is too low to reach the destination at all, it can lead to slow routing performance. 
   * @return maxTransfers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_TRANSFERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxTransfers() {
    return maxTransfers;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_TRANSFERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxTransfers(@jakarta.annotation.Nullable Integer maxTransfers) {
    this.maxTransfers = maxTransfers;
  }

  public OneToManyIntermodalParams minTransferTime(@jakarta.annotation.Nullable Integer minTransferTime) {
    
    this.minTransferTime = minTransferTime;
    return this;
  }

  /**
   * Optional. Default is 0 minutes.  Minimum transfer time for each transfer in minutes. 
   * @return minTransferTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIN_TRANSFER_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMinTransferTime() {
    return minTransferTime;
  }


  @JsonProperty(value = JSON_PROPERTY_MIN_TRANSFER_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinTransferTime(@jakarta.annotation.Nullable Integer minTransferTime) {
    this.minTransferTime = minTransferTime;
  }

  public OneToManyIntermodalParams additionalTransferTime(@jakarta.annotation.Nullable Integer additionalTransferTime) {
    
    this.additionalTransferTime = additionalTransferTime;
    return this;
  }

  /**
   * Optional. Default is 0 minutes.  Additional transfer time reserved for each transfer in minutes. 
   * @return additionalTransferTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_TRANSFER_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAdditionalTransferTime() {
    return additionalTransferTime;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDITIONAL_TRANSFER_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalTransferTime(@jakarta.annotation.Nullable Integer additionalTransferTime) {
    this.additionalTransferTime = additionalTransferTime;
  }

  public OneToManyIntermodalParams transferTimeFactor(@jakarta.annotation.Nullable BigDecimal transferTimeFactor) {
    
    this.transferTimeFactor = transferTimeFactor;
    return this;
  }

  /**
   * Optional. Default is 1.0  Factor to multiply minimum required transfer times with. Values smaller than 1.0 are not supported. 
   * @return transferTimeFactor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSFER_TIME_FACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTransferTimeFactor() {
    return transferTimeFactor;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSFER_TIME_FACTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransferTimeFactor(@jakarta.annotation.Nullable BigDecimal transferTimeFactor) {
    this.transferTimeFactor = transferTimeFactor;
  }

  public OneToManyIntermodalParams useRoutedTransfers(@jakarta.annotation.Nullable Boolean useRoutedTransfers) {
    
    this.useRoutedTransfers = useRoutedTransfers;
    return this;
  }

  /**
   * Optional. Default is &#x60;false&#x60;.  Whether to use transfers routed on OpenStreetMap data. 
   * @return useRoutedTransfers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USE_ROUTED_TRANSFERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseRoutedTransfers() {
    return useRoutedTransfers;
  }


  @JsonProperty(value = JSON_PROPERTY_USE_ROUTED_TRANSFERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseRoutedTransfers(@jakarta.annotation.Nullable Boolean useRoutedTransfers) {
    this.useRoutedTransfers = useRoutedTransfers;
  }

  public OneToManyIntermodalParams pedestrianProfile(@jakarta.annotation.Nullable PedestrianProfile pedestrianProfile) {
    
    this.pedestrianProfile = pedestrianProfile;
    return this;
  }

  /**
   * Optional. Default is &#x60;FOOT&#x60;.  Accessibility profile to use for pedestrian routing in transfers between transit connections and the first and last mile respectively. 
   * @return pedestrianProfile
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PEDESTRIAN_PROFILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PedestrianProfile getPedestrianProfile() {
    return pedestrianProfile;
  }


  @JsonProperty(value = JSON_PROPERTY_PEDESTRIAN_PROFILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPedestrianProfile(@jakarta.annotation.Nullable PedestrianProfile pedestrianProfile) {
    this.pedestrianProfile = pedestrianProfile;
  }

  public OneToManyIntermodalParams pedestrianSpeed(@jakarta.annotation.Nullable BigDecimal pedestrianSpeed) {
    
    this.pedestrianSpeed = pedestrianSpeed;
    return this;
  }

  /**
   * Optional  Average speed for pedestrian routing. 
   * @return pedestrianSpeed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PEDESTRIAN_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPedestrianSpeed() {
    return pedestrianSpeed;
  }


  @JsonProperty(value = JSON_PROPERTY_PEDESTRIAN_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPedestrianSpeed(@jakarta.annotation.Nullable BigDecimal pedestrianSpeed) {
    this.pedestrianSpeed = pedestrianSpeed;
  }

  public OneToManyIntermodalParams cyclingSpeed(@jakarta.annotation.Nullable BigDecimal cyclingSpeed) {
    
    this.cyclingSpeed = cyclingSpeed;
    return this;
  }

  /**
   * Optional  Average speed for bike routing. 
   * @return cyclingSpeed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CYCLING_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCyclingSpeed() {
    return cyclingSpeed;
  }


  @JsonProperty(value = JSON_PROPERTY_CYCLING_SPEED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCyclingSpeed(@jakarta.annotation.Nullable BigDecimal cyclingSpeed) {
    this.cyclingSpeed = cyclingSpeed;
  }

  public OneToManyIntermodalParams elevationCosts(@jakarta.annotation.Nullable ElevationCosts elevationCosts) {
    
    this.elevationCosts = elevationCosts;
    return this;
  }

  /**
   * Optional. Default is &#x60;NONE&#x60;.  Set an elevation cost profile, to penalize routes with incline. - &#x60;NONE&#x60;: No additional costs for elevations. This is the default behavior - &#x60;LOW&#x60;: Add a low cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if small detours are required. - &#x60;HIGH&#x60;: Add a high cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if larger detours are required.  As using an elevation costs profile will increase the travel duration, routing through steep terrain may exceed the maximal allowed duration, causing a location to appear unreachable. Increasing the maximum travel time for these segments may resolve this issue.  The profile is used for routing on both the first and last mile.  Elevation cost profiles are currently used by following street modes: - &#x60;BIKE&#x60; 
   * @return elevationCosts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELEVATION_COSTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ElevationCosts getElevationCosts() {
    return elevationCosts;
  }


  @JsonProperty(value = JSON_PROPERTY_ELEVATION_COSTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElevationCosts(@jakarta.annotation.Nullable ElevationCosts elevationCosts) {
    this.elevationCosts = elevationCosts;
  }

  public OneToManyIntermodalParams transitModes(@jakarta.annotation.Nullable List<Mode> transitModes) {
    
    this.transitModes = transitModes;
    return this;
  }

  public OneToManyIntermodalParams addTransitModesItem(Mode transitModesItem) {
    if (this.transitModes == null) {
      this.transitModes = new ArrayList<>(Arrays.asList(Mode.TRANSIT));
    }
    this.transitModes.add(transitModesItem);
    return this;
  }

  /**
   * Optional. Default is &#x60;TRANSIT&#x60; which allows all transit modes (no restriction). Allowed modes for the transit part. If empty, no transit connections will be computed. For example, this can be used to allow only &#x60;SUBURBAN,SUBWAY,TRAM&#x60;. 
   * @return transitModes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRANSIT_MODES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Mode> getTransitModes() {
    return transitModes;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSIT_MODES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransitModes(@jakarta.annotation.Nullable List<Mode> transitModes) {
    this.transitModes = transitModes;
  }

  public OneToManyIntermodalParams preTransitModes(@jakarta.annotation.Nullable List<Mode> preTransitModes) {
    
    this.preTransitModes = preTransitModes;
    return this;
  }

  public OneToManyIntermodalParams addPreTransitModesItem(Mode preTransitModesItem) {
    if (this.preTransitModes == null) {
      this.preTransitModes = new ArrayList<>(Arrays.asList(Mode.WALK));
    }
    this.preTransitModes.add(preTransitModesItem);
    return this;
  }

  /**
   * Optional. Default is &#x60;WALK&#x60;. Does not apply to direct connections (see &#x60;directMode&#x60;).  A list of modes that are allowed to be used for the first mile, i.e. from the coordinates to the first transit stop. Example: &#x60;WALK,BIKE_SHARING&#x60;. 
   * @return preTransitModes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRE_TRANSIT_MODES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Mode> getPreTransitModes() {
    return preTransitModes;
  }


  @JsonProperty(value = JSON_PROPERTY_PRE_TRANSIT_MODES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreTransitModes(@jakarta.annotation.Nullable List<Mode> preTransitModes) {
    this.preTransitModes = preTransitModes;
  }

  public OneToManyIntermodalParams postTransitModes(@jakarta.annotation.Nullable List<Mode> postTransitModes) {
    
    this.postTransitModes = postTransitModes;
    return this;
  }

  public OneToManyIntermodalParams addPostTransitModesItem(Mode postTransitModesItem) {
    if (this.postTransitModes == null) {
      this.postTransitModes = new ArrayList<>(Arrays.asList(Mode.WALK));
    }
    this.postTransitModes.add(postTransitModesItem);
    return this;
  }

  /**
   * Optional. Default is &#x60;WALK&#x60;. Does not apply to direct connections (see &#x60;directMode&#x60;).  A list of modes that are allowed to be used for the last mile, i.e. from the last transit stop to the target coordinates. Example: &#x60;WALK,BIKE_SHARING&#x60;. 
   * @return postTransitModes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POST_TRANSIT_MODES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Mode> getPostTransitModes() {
    return postTransitModes;
  }


  @JsonProperty(value = JSON_PROPERTY_POST_TRANSIT_MODES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostTransitModes(@jakarta.annotation.Nullable List<Mode> postTransitModes) {
    this.postTransitModes = postTransitModes;
  }

  public OneToManyIntermodalParams directMode(@jakarta.annotation.Nullable Mode directMode) {
    
    this.directMode = directMode;
    return this;
  }

  /**
   * Default is &#x60;WALK&#x60; which will compute walking routes as direct connections.  Mode used for direction connections from start to destination without using transit.  Currently supported non-transit modes: \\&#x60;WALK\\&#x60;, \\&#x60;BIKE\\&#x60;, \\&#x60;CAR\\&#x60; 
   * @return directMode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIRECT_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Mode getDirectMode() {
    return directMode;
  }


  @JsonProperty(value = JSON_PROPERTY_DIRECT_MODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirectMode(@jakarta.annotation.Nullable Mode directMode) {
    this.directMode = directMode;
  }

  public OneToManyIntermodalParams maxPreTransitTime(@jakarta.annotation.Nullable Integer maxPreTransitTime) {
    
    this.maxPreTransitTime = maxPreTransitTime;
    return this;
  }

  /**
   * Optional. Default is 15min which is &#x60;900&#x60;. Maximum time in seconds for the first street leg. Is limited by server config variable &#x60;street_routing_max_prepost_transit_seconds&#x60;. 
   * minimum: 0
   * @return maxPreTransitTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_PRE_TRANSIT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxPreTransitTime() {
    return maxPreTransitTime;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_PRE_TRANSIT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxPreTransitTime(@jakarta.annotation.Nullable Integer maxPreTransitTime) {
    this.maxPreTransitTime = maxPreTransitTime;
  }

  public OneToManyIntermodalParams maxPostTransitTime(@jakarta.annotation.Nullable Integer maxPostTransitTime) {
    
    this.maxPostTransitTime = maxPostTransitTime;
    return this;
  }

  /**
   * Optional. Default is 15min which is &#x60;900&#x60;. Maximum time in seconds for the last street leg. Is limited by server config variable &#x60;street_routing_max_prepost_transit_seconds&#x60;. 
   * minimum: 0
   * @return maxPostTransitTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_POST_TRANSIT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxPostTransitTime() {
    return maxPostTransitTime;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_POST_TRANSIT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxPostTransitTime(@jakarta.annotation.Nullable Integer maxPostTransitTime) {
    this.maxPostTransitTime = maxPostTransitTime;
  }

  public OneToManyIntermodalParams maxDirectTime(@jakarta.annotation.Nullable Integer maxDirectTime) {
    
    this.maxDirectTime = maxDirectTime;
    return this;
  }

  /**
   * Optional. Default is 30min which is &#x60;1800&#x60;. Maximum time in seconds for direct connections.  If a value smaller than either &#x60;maxPreTransitTime&#x60; or &#x60;maxPostTransitTime&#x60; is used, their maximum is set instead. Is limited by server config variable &#x60;street_routing_max_direct_seconds&#x60;. 
   * minimum: 0
   * @return maxDirectTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_DIRECT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxDirectTime() {
    return maxDirectTime;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_DIRECT_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxDirectTime(@jakarta.annotation.Nullable Integer maxDirectTime) {
    this.maxDirectTime = maxDirectTime;
  }

  public OneToManyIntermodalParams withDistance(@jakarta.annotation.Nullable Boolean withDistance) {
    
    this.withDistance = withDistance;
    return this;
  }

  /**
   * If true, the response includes the distance in meters for each path. This requires path reconstruction and may be slower than duration-only queries.  &#x60;withDistance&#x60; is currently limited to street routing. 
   * @return withDistance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WITH_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getWithDistance() {
    return withDistance;
  }


  @JsonProperty(value = JSON_PROPERTY_WITH_DISTANCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWithDistance(@jakarta.annotation.Nullable Boolean withDistance) {
    this.withDistance = withDistance;
  }

  public OneToManyIntermodalParams requireBikeTransport(@jakarta.annotation.Nullable Boolean requireBikeTransport) {
    
    this.requireBikeTransport = requireBikeTransport;
    return this;
  }

  /**
   * Optional. Default is &#x60;false&#x60;.  If set to &#x60;true&#x60;, all used transit trips are required to allow bike carriage. 
   * @return requireBikeTransport
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUIRE_BIKE_TRANSPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRequireBikeTransport() {
    return requireBikeTransport;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRE_BIKE_TRANSPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequireBikeTransport(@jakarta.annotation.Nullable Boolean requireBikeTransport) {
    this.requireBikeTransport = requireBikeTransport;
  }

  public OneToManyIntermodalParams requireCarTransport(@jakarta.annotation.Nullable Boolean requireCarTransport) {
    
    this.requireCarTransport = requireCarTransport;
    return this;
  }

  /**
   * Optional. Default is &#x60;false&#x60;.  If set to &#x60;true&#x60;, all used transit trips are required to allow car carriage. 
   * @return requireCarTransport
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUIRE_CAR_TRANSPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRequireCarTransport() {
    return requireCarTransport;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUIRE_CAR_TRANSPORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequireCarTransport(@jakarta.annotation.Nullable Boolean requireCarTransport) {
    this.requireCarTransport = requireCarTransport;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OneToManyIntermodalParams oneToManyIntermodalParams = (OneToManyIntermodalParams) o;
    return Objects.equals(this.one, oneToManyIntermodalParams.one) &&
        Objects.equals(this.many, oneToManyIntermodalParams.many) &&
        Objects.equals(this.time, oneToManyIntermodalParams.time) &&
        Objects.equals(this.maxTravelTime, oneToManyIntermodalParams.maxTravelTime) &&
        Objects.equals(this.maxMatchingDistance, oneToManyIntermodalParams.maxMatchingDistance) &&
        Objects.equals(this.arriveBy, oneToManyIntermodalParams.arriveBy) &&
        Objects.equals(this.maxTransfers, oneToManyIntermodalParams.maxTransfers) &&
        Objects.equals(this.minTransferTime, oneToManyIntermodalParams.minTransferTime) &&
        Objects.equals(this.additionalTransferTime, oneToManyIntermodalParams.additionalTransferTime) &&
        Objects.equals(this.transferTimeFactor, oneToManyIntermodalParams.transferTimeFactor) &&
        Objects.equals(this.useRoutedTransfers, oneToManyIntermodalParams.useRoutedTransfers) &&
        Objects.equals(this.pedestrianProfile, oneToManyIntermodalParams.pedestrianProfile) &&
        Objects.equals(this.pedestrianSpeed, oneToManyIntermodalParams.pedestrianSpeed) &&
        Objects.equals(this.cyclingSpeed, oneToManyIntermodalParams.cyclingSpeed) &&
        Objects.equals(this.elevationCosts, oneToManyIntermodalParams.elevationCosts) &&
        Objects.equals(this.transitModes, oneToManyIntermodalParams.transitModes) &&
        Objects.equals(this.preTransitModes, oneToManyIntermodalParams.preTransitModes) &&
        Objects.equals(this.postTransitModes, oneToManyIntermodalParams.postTransitModes) &&
        Objects.equals(this.directMode, oneToManyIntermodalParams.directMode) &&
        Objects.equals(this.maxPreTransitTime, oneToManyIntermodalParams.maxPreTransitTime) &&
        Objects.equals(this.maxPostTransitTime, oneToManyIntermodalParams.maxPostTransitTime) &&
        Objects.equals(this.maxDirectTime, oneToManyIntermodalParams.maxDirectTime) &&
        Objects.equals(this.withDistance, oneToManyIntermodalParams.withDistance) &&
        Objects.equals(this.requireBikeTransport, oneToManyIntermodalParams.requireBikeTransport) &&
        Objects.equals(this.requireCarTransport, oneToManyIntermodalParams.requireCarTransport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(one, many, time, maxTravelTime, maxMatchingDistance, arriveBy, maxTransfers, minTransferTime, additionalTransferTime, transferTimeFactor, useRoutedTransfers, pedestrianProfile, pedestrianSpeed, cyclingSpeed, elevationCosts, transitModes, preTransitModes, postTransitModes, directMode, maxPreTransitTime, maxPostTransitTime, maxDirectTime, withDistance, requireBikeTransport, requireCarTransport);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OneToManyIntermodalParams {\n");
    sb.append("    one: ").append(toIndentedString(one)).append("\n");
    sb.append("    many: ").append(toIndentedString(many)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    maxTravelTime: ").append(toIndentedString(maxTravelTime)).append("\n");
    sb.append("    maxMatchingDistance: ").append(toIndentedString(maxMatchingDistance)).append("\n");
    sb.append("    arriveBy: ").append(toIndentedString(arriveBy)).append("\n");
    sb.append("    maxTransfers: ").append(toIndentedString(maxTransfers)).append("\n");
    sb.append("    minTransferTime: ").append(toIndentedString(minTransferTime)).append("\n");
    sb.append("    additionalTransferTime: ").append(toIndentedString(additionalTransferTime)).append("\n");
    sb.append("    transferTimeFactor: ").append(toIndentedString(transferTimeFactor)).append("\n");
    sb.append("    useRoutedTransfers: ").append(toIndentedString(useRoutedTransfers)).append("\n");
    sb.append("    pedestrianProfile: ").append(toIndentedString(pedestrianProfile)).append("\n");
    sb.append("    pedestrianSpeed: ").append(toIndentedString(pedestrianSpeed)).append("\n");
    sb.append("    cyclingSpeed: ").append(toIndentedString(cyclingSpeed)).append("\n");
    sb.append("    elevationCosts: ").append(toIndentedString(elevationCosts)).append("\n");
    sb.append("    transitModes: ").append(toIndentedString(transitModes)).append("\n");
    sb.append("    preTransitModes: ").append(toIndentedString(preTransitModes)).append("\n");
    sb.append("    postTransitModes: ").append(toIndentedString(postTransitModes)).append("\n");
    sb.append("    directMode: ").append(toIndentedString(directMode)).append("\n");
    sb.append("    maxPreTransitTime: ").append(toIndentedString(maxPreTransitTime)).append("\n");
    sb.append("    maxPostTransitTime: ").append(toIndentedString(maxPostTransitTime)).append("\n");
    sb.append("    maxDirectTime: ").append(toIndentedString(maxDirectTime)).append("\n");
    sb.append("    withDistance: ").append(toIndentedString(withDistance)).append("\n");
    sb.append("    requireBikeTransport: ").append(toIndentedString(requireBikeTransport)).append("\n");
    sb.append("    requireCarTransport: ").append(toIndentedString(requireCarTransport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

