/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Object containing a single element of a ParetoSet
 */
@JsonPropertyOrder({
  ParetoSetEntry.JSON_PROPERTY_DURATION,
  ParetoSetEntry.JSON_PROPERTY_TRANSFERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class ParetoSetEntry {
  public static final String JSON_PROPERTY_DURATION = "duration";
  @jakarta.annotation.Nonnull
  private BigDecimal duration;

  public static final String JSON_PROPERTY_TRANSFERS = "transfers";
  @jakarta.annotation.Nonnull
  private Integer transfers;

  public ParetoSetEntry() {
  }

  public ParetoSetEntry duration(@jakarta.annotation.Nonnull BigDecimal duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * duration in seconds for the the best solution using &#x60;transfer&#x60; transfers  Notice that the resolution is currently in minutes, because of implementation details 
   * minimum: 0.0
   * @return duration
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DURATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getDuration() {
    return duration;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDuration(@jakarta.annotation.Nonnull BigDecimal duration) {
    this.duration = duration;
  }

  public ParetoSetEntry transfers(@jakarta.annotation.Nonnull Integer transfers) {
    
    this.transfers = transfers;
    return this;
  }

  /**
   * The minimal number of transfers required to arrive within &#x60;duration&#x60; seconds  transfers&#x3D;0: Direct transit connecion without any transfers transfers&#x3D;1: Transit connection with 1 transfer 
   * minimum: 0
   * @return transfers
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSFERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTransfers() {
    return transfers;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSFERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransfers(@jakarta.annotation.Nonnull Integer transfers) {
    this.transfers = transfers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParetoSetEntry paretoSetEntry = (ParetoSetEntry) o;
    return Objects.equals(this.duration, paretoSetEntry.duration) &&
        Objects.equals(this.transfers, paretoSetEntry.transfers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, transfers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParetoSetEntry {\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    transfers: ").append(toIndentedString(transfers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

