/*
 * MOTIS API
 * This is the MOTIS routing API.
 *
 * The version of the OpenAPI document: v4
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets RentalFormFactor
 */
public enum RentalFormFactor {
  
  BICYCLE("BICYCLE"),
  
  CARGO_BICYCLE("CARGO_BICYCLE"),
  
  CAR("CAR"),
  
  MOPED("MOPED"),
  
  SCOOTER_STANDING("SCOOTER_STANDING"),
  
  SCOOTER_SEATED("SCOOTER_SEATED"),
  
  OTHER("OTHER");

  private String value;

  RentalFormFactor(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static RentalFormFactor fromValue(String value) {
    for (RentalFormFactor b : RentalFormFactor.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

