/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Mode;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * a transit route/line serving a stop
 */
@JsonPropertyOrder({
  Route.JSON_PROPERTY_ROUTE_ID,
  Route.JSON_PROPERTY_ROUTE_SHORT_NAME,
  Route.JSON_PROPERTY_ROUTE_LONG_NAME,
  Route.JSON_PROPERTY_MODE,
  Route.JSON_PROPERTY_AGENCY_ID,
  Route.JSON_PROPERTY_AGENCY_NAME,
  Route.JSON_PROPERTY_AGENCY_URL,
  Route.JSON_PROPERTY_ROUTE_COLOR,
  Route.JSON_PROPERTY_ROUTE_TEXT_COLOR,
  Route.JSON_PROPERTY_ROUTE_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Route {
  public static final String JSON_PROPERTY_ROUTE_ID = "routeId";
  @jakarta.annotation.Nonnull
  private String routeId;

  public static final String JSON_PROPERTY_ROUTE_SHORT_NAME = "routeShortName";
  @jakarta.annotation.Nonnull
  private String routeShortName;

  public static final String JSON_PROPERTY_ROUTE_LONG_NAME = "routeLongName";
  @jakarta.annotation.Nonnull
  private String routeLongName;

  public static final String JSON_PROPERTY_MODE = "mode";
  @jakarta.annotation.Nonnull
  private Mode mode;

  public static final String JSON_PROPERTY_AGENCY_ID = "agencyId";
  @jakarta.annotation.Nonnull
  private String agencyId;

  public static final String JSON_PROPERTY_AGENCY_NAME = "agencyName";
  @jakarta.annotation.Nonnull
  private String agencyName;

  public static final String JSON_PROPERTY_AGENCY_URL = "agencyUrl";
  @jakarta.annotation.Nonnull
  private String agencyUrl;

  public static final String JSON_PROPERTY_ROUTE_COLOR = "routeColor";
  @jakarta.annotation.Nullable
  private String routeColor;

  public static final String JSON_PROPERTY_ROUTE_TEXT_COLOR = "routeTextColor";
  @jakarta.annotation.Nullable
  private String routeTextColor;

  public static final String JSON_PROPERTY_ROUTE_TYPE = "routeType";
  @jakarta.annotation.Nullable
  private Integer routeType;

  public Route() {
  }

  public Route routeId(@jakarta.annotation.Nonnull String routeId) {
    
    this.routeId = routeId;
    return this;
  }

  /**
   * Get routeId
   * @return routeId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROUTE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRouteId() {
    return routeId;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteId(@jakarta.annotation.Nonnull String routeId) {
    this.routeId = routeId;
  }

  public Route routeShortName(@jakarta.annotation.Nonnull String routeShortName) {
    
    this.routeShortName = routeShortName;
    return this;
  }

  /**
   * Get routeShortName
   * @return routeShortName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROUTE_SHORT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRouteShortName() {
    return routeShortName;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_SHORT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteShortName(@jakarta.annotation.Nonnull String routeShortName) {
    this.routeShortName = routeShortName;
  }

  public Route routeLongName(@jakarta.annotation.Nonnull String routeLongName) {
    
    this.routeLongName = routeLongName;
    return this;
  }

  /**
   * Get routeLongName
   * @return routeLongName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROUTE_LONG_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRouteLongName() {
    return routeLongName;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_LONG_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteLongName(@jakarta.annotation.Nonnull String routeLongName) {
    this.routeLongName = routeLongName;
  }

  public Route mode(@jakarta.annotation.Nonnull Mode mode) {
    
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Mode getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMode(@jakarta.annotation.Nonnull Mode mode) {
    this.mode = mode;
  }

  public Route agencyId(@jakarta.annotation.Nonnull String agencyId) {
    
    this.agencyId = agencyId;
    return this;
  }

  /**
   * Get agencyId
   * @return agencyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AGENCY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgencyId() {
    return agencyId;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENCY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgencyId(@jakarta.annotation.Nonnull String agencyId) {
    this.agencyId = agencyId;
  }

  public Route agencyName(@jakarta.annotation.Nonnull String agencyName) {
    
    this.agencyName = agencyName;
    return this;
  }

  /**
   * Get agencyName
   * @return agencyName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AGENCY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgencyName() {
    return agencyName;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENCY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgencyName(@jakarta.annotation.Nonnull String agencyName) {
    this.agencyName = agencyName;
  }

  public Route agencyUrl(@jakarta.annotation.Nonnull String agencyUrl) {
    
    this.agencyUrl = agencyUrl;
    return this;
  }

  /**
   * Get agencyUrl
   * @return agencyUrl
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AGENCY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgencyUrl() {
    return agencyUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENCY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgencyUrl(@jakarta.annotation.Nonnull String agencyUrl) {
    this.agencyUrl = agencyUrl;
  }

  public Route routeColor(@jakarta.annotation.Nullable String routeColor) {
    
    this.routeColor = routeColor;
    return this;
  }

  /**
   * Get routeColor
   * @return routeColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROUTE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRouteColor() {
    return routeColor;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteColor(@jakarta.annotation.Nullable String routeColor) {
    this.routeColor = routeColor;
  }

  public Route routeTextColor(@jakarta.annotation.Nullable String routeTextColor) {
    
    this.routeTextColor = routeTextColor;
    return this;
  }

  /**
   * Get routeTextColor
   * @return routeTextColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROUTE_TEXT_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRouteTextColor() {
    return routeTextColor;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_TEXT_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteTextColor(@jakarta.annotation.Nullable String routeTextColor) {
    this.routeTextColor = routeTextColor;
  }

  public Route routeType(@jakarta.annotation.Nullable Integer routeType) {
    
    this.routeType = routeType;
    return this;
  }

  /**
   * Get routeType
   * @return routeType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROUTE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRouteType() {
    return routeType;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteType(@jakarta.annotation.Nullable Integer routeType) {
    this.routeType = routeType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Route route = (Route) o;
    return Objects.equals(this.routeId, route.routeId) &&
        Objects.equals(this.routeShortName, route.routeShortName) &&
        Objects.equals(this.routeLongName, route.routeLongName) &&
        Objects.equals(this.mode, route.mode) &&
        Objects.equals(this.agencyId, route.agencyId) &&
        Objects.equals(this.agencyName, route.agencyName) &&
        Objects.equals(this.agencyUrl, route.agencyUrl) &&
        Objects.equals(this.routeColor, route.routeColor) &&
        Objects.equals(this.routeTextColor, route.routeTextColor) &&
        Objects.equals(this.routeType, route.routeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routeId, routeShortName, routeLongName, mode, agencyId, agencyName, agencyUrl, routeColor, routeTextColor, routeType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Route {\n");
    sb.append("    routeId: ").append(toIndentedString(routeId)).append("\n");
    sb.append("    routeShortName: ").append(toIndentedString(routeShortName)).append("\n");
    sb.append("    routeLongName: ").append(toIndentedString(routeLongName)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    agencyId: ").append(toIndentedString(agencyId)).append("\n");
    sb.append("    agencyName: ").append(toIndentedString(agencyName)).append("\n");
    sb.append("    agencyUrl: ").append(toIndentedString(agencyUrl)).append("\n");
    sb.append("    routeColor: ").append(toIndentedString(routeColor)).append("\n");
    sb.append("    routeTextColor: ").append(toIndentedString(routeTextColor)).append("\n");
    sb.append("    routeType: ").append(toIndentedString(routeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

