/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Mode;
import dev.bileto.motis.client.model.RoutePathSource;
import dev.bileto.motis.client.model.RouteSegment;
import dev.bileto.motis.client.model.TransitRouteInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RouteInfo
 */
@JsonPropertyOrder({
  RouteInfo.JSON_PROPERTY_MODE,
  RouteInfo.JSON_PROPERTY_TRANSIT_ROUTES,
  RouteInfo.JSON_PROPERTY_NUM_STOPS,
  RouteInfo.JSON_PROPERTY_ROUTE_IDX,
  RouteInfo.JSON_PROPERTY_PATH_SOURCE,
  RouteInfo.JSON_PROPERTY_SEGMENTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class RouteInfo {
  public static final String JSON_PROPERTY_MODE = "mode";
  @jakarta.annotation.Nonnull
  private Mode mode;

  public static final String JSON_PROPERTY_TRANSIT_ROUTES = "transitRoutes";
  @jakarta.annotation.Nonnull
  private List<TransitRouteInfo> transitRoutes = new ArrayList<>();

  public static final String JSON_PROPERTY_NUM_STOPS = "numStops";
  @jakarta.annotation.Nonnull
  private Integer numStops;

  public static final String JSON_PROPERTY_ROUTE_IDX = "routeIdx";
  @jakarta.annotation.Nonnull
  private Integer routeIdx;

  public static final String JSON_PROPERTY_PATH_SOURCE = "pathSource";
  @jakarta.annotation.Nonnull
  private RoutePathSource pathSource;

  public static final String JSON_PROPERTY_SEGMENTS = "segments";
  @jakarta.annotation.Nonnull
  private List<RouteSegment> segments = new ArrayList<>();

  public RouteInfo() {
  }

  public RouteInfo mode(@jakarta.annotation.Nonnull Mode mode) {
    
    this.mode = mode;
    return this;
  }

  /**
   * Transport mode for this route
   * @return mode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Mode getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMode(@jakarta.annotation.Nonnull Mode mode) {
    this.mode = mode;
  }

  public RouteInfo transitRoutes(@jakarta.annotation.Nonnull List<TransitRouteInfo> transitRoutes) {
    
    this.transitRoutes = transitRoutes;
    return this;
  }

  public RouteInfo addTransitRoutesItem(TransitRouteInfo transitRoutesItem) {
    if (this.transitRoutes == null) {
      this.transitRoutes = new ArrayList<>();
    }
    this.transitRoutes.add(transitRoutesItem);
    return this;
  }

  /**
   * Get transitRoutes
   * @return transitRoutes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSIT_ROUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TransitRouteInfo> getTransitRoutes() {
    return transitRoutes;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSIT_ROUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransitRoutes(@jakarta.annotation.Nonnull List<TransitRouteInfo> transitRoutes) {
    this.transitRoutes = transitRoutes;
  }

  public RouteInfo numStops(@jakarta.annotation.Nonnull Integer numStops) {
    
    this.numStops = numStops;
    return this;
  }

  /**
   * Number of stops along this route
   * @return numStops
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NUM_STOPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getNumStops() {
    return numStops;
  }


  @JsonProperty(value = JSON_PROPERTY_NUM_STOPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNumStops(@jakarta.annotation.Nonnull Integer numStops) {
    this.numStops = numStops;
  }

  public RouteInfo routeIdx(@jakarta.annotation.Nonnull Integer routeIdx) {
    
    this.routeIdx = routeIdx;
    return this;
  }

  /**
   * Internal route index for debugging purposes
   * @return routeIdx
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROUTE_IDX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRouteIdx() {
    return routeIdx;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_IDX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteIdx(@jakarta.annotation.Nonnull Integer routeIdx) {
    this.routeIdx = routeIdx;
  }

  public RouteInfo pathSource(@jakarta.annotation.Nonnull RoutePathSource pathSource) {
    
    this.pathSource = pathSource;
    return this;
  }

  /**
   * Get pathSource
   * @return pathSource
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATH_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RoutePathSource getPathSource() {
    return pathSource;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH_SOURCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPathSource(@jakarta.annotation.Nonnull RoutePathSource pathSource) {
    this.pathSource = pathSource;
  }

  public RouteInfo segments(@jakarta.annotation.Nonnull List<RouteSegment> segments) {
    
    this.segments = segments;
    return this;
  }

  public RouteInfo addSegmentsItem(RouteSegment segmentsItem) {
    if (this.segments == null) {
      this.segments = new ArrayList<>();
    }
    this.segments.add(segmentsItem);
    return this;
  }

  /**
   * Get segments
   * @return segments
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEGMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RouteSegment> getSegments() {
    return segments;
  }


  @JsonProperty(value = JSON_PROPERTY_SEGMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSegments(@jakarta.annotation.Nonnull List<RouteSegment> segments) {
    this.segments = segments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteInfo routeInfo = (RouteInfo) o;
    return Objects.equals(this.mode, routeInfo.mode) &&
        Objects.equals(this.transitRoutes, routeInfo.transitRoutes) &&
        Objects.equals(this.numStops, routeInfo.numStops) &&
        Objects.equals(this.routeIdx, routeInfo.routeIdx) &&
        Objects.equals(this.pathSource, routeInfo.pathSource) &&
        Objects.equals(this.segments, routeInfo.segments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mode, transitRoutes, numStops, routeIdx, pathSource, segments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteInfo {\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    transitRoutes: ").append(toIndentedString(transitRoutes)).append("\n");
    sb.append("    numStops: ").append(toIndentedString(numStops)).append("\n");
    sb.append("    routeIdx: ").append(toIndentedString(routeIdx)).append("\n");
    sb.append("    pathSource: ").append(toIndentedString(pathSource)).append("\n");
    sb.append("    segments: ").append(toIndentedString(segments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

