/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.EncodedPolyline;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Shared polyline used by one or more route segments
 */
@JsonPropertyOrder({
  RoutePolyline.JSON_PROPERTY_POLYLINE,
  RoutePolyline.JSON_PROPERTY_COLORS,
  RoutePolyline.JSON_PROPERTY_ROUTE_INDEXES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class RoutePolyline {
  public static final String JSON_PROPERTY_POLYLINE = "polyline";
  @jakarta.annotation.Nonnull
  private EncodedPolyline polyline;

  public static final String JSON_PROPERTY_COLORS = "colors";
  @jakarta.annotation.Nonnull
  private List<String> colors = new ArrayList<>();

  public static final String JSON_PROPERTY_ROUTE_INDEXES = "routeIndexes";
  @jakarta.annotation.Nonnull
  private List<Integer> routeIndexes = new ArrayList<>();

  public RoutePolyline() {
  }

  public RoutePolyline polyline(@jakarta.annotation.Nonnull EncodedPolyline polyline) {
    
    this.polyline = polyline;
    return this;
  }

  /**
   * Get polyline
   * @return polyline
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POLYLINE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EncodedPolyline getPolyline() {
    return polyline;
  }


  @JsonProperty(value = JSON_PROPERTY_POLYLINE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolyline(@jakarta.annotation.Nonnull EncodedPolyline polyline) {
    this.polyline = polyline;
  }

  public RoutePolyline colors(@jakarta.annotation.Nonnull List<String> colors) {
    
    this.colors = colors;
    return this;
  }

  public RoutePolyline addColorsItem(String colorsItem) {
    if (this.colors == null) {
      this.colors = new ArrayList<>();
    }
    this.colors.add(colorsItem);
    return this;
  }

  /**
   * Unique route colors of routes containing this segment
   * @return colors
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COLORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getColors() {
    return colors;
  }


  @JsonProperty(value = JSON_PROPERTY_COLORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColors(@jakarta.annotation.Nonnull List<String> colors) {
    this.colors = colors;
  }

  public RoutePolyline routeIndexes(@jakarta.annotation.Nonnull List<Integer> routeIndexes) {
    
    this.routeIndexes = routeIndexes;
    return this;
  }

  public RoutePolyline addRouteIndexesItem(Integer routeIndexesItem) {
    if (this.routeIndexes == null) {
      this.routeIndexes = new ArrayList<>();
    }
    this.routeIndexes.add(routeIndexesItem);
    return this;
  }

  /**
   * Indexes into the top-level routes array for routes containing this segment
   * @return routeIndexes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROUTE_INDEXES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Integer> getRouteIndexes() {
    return routeIndexes;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTE_INDEXES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteIndexes(@jakarta.annotation.Nonnull List<Integer> routeIndexes) {
    this.routeIndexes = routeIndexes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RoutePolyline routePolyline = (RoutePolyline) o;
    return Objects.equals(this.polyline, routePolyline.polyline) &&
        Objects.equals(this.colors, routePolyline.colors) &&
        Objects.equals(this.routeIndexes, routePolyline.routeIndexes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(polyline, colors, routeIndexes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RoutePolyline {\n");
    sb.append("    polyline: ").append(toIndentedString(polyline)).append("\n");
    sb.append("    colors: ").append(toIndentedString(colors)).append("\n");
    sb.append("    routeIndexes: ").append(toIndentedString(routeIndexes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

