/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Place;
import dev.bileto.motis.client.model.RouteInfo;
import dev.bileto.motis.client.model.RoutePolyline;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RouteDetails200Response
 */
@JsonPropertyOrder({
  RouteDetails200Response.JSON_PROPERTY_ROUTES,
  RouteDetails200Response.JSON_PROPERTY_POLYLINES,
  RouteDetails200Response.JSON_PROPERTY_STOPS,
  RouteDetails200Response.JSON_PROPERTY_ZOOM_FILTERED
})
@JsonTypeName("routeDetails_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class RouteDetails200Response {
  public static final String JSON_PROPERTY_ROUTES = "routes";
  @jakarta.annotation.Nonnull
  private List<RouteInfo> routes = new ArrayList<>();

  public static final String JSON_PROPERTY_POLYLINES = "polylines";
  @jakarta.annotation.Nonnull
  private List<RoutePolyline> polylines = new ArrayList<>();

  public static final String JSON_PROPERTY_STOPS = "stops";
  @jakarta.annotation.Nonnull
  private List<Place> stops = new ArrayList<>();

  public static final String JSON_PROPERTY_ZOOM_FILTERED = "zoomFiltered";
  @jakarta.annotation.Nonnull
  private Boolean zoomFiltered;

  public RouteDetails200Response() {
  }

  public RouteDetails200Response routes(@jakarta.annotation.Nonnull List<RouteInfo> routes) {
    
    this.routes = routes;
    return this;
  }

  public RouteDetails200Response addRoutesItem(RouteInfo routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<>();
    }
    this.routes.add(routesItem);
    return this;
  }

  /**
   * Get routes
   * @return routes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RouteInfo> getRoutes() {
    return routes;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoutes(@jakarta.annotation.Nonnull List<RouteInfo> routes) {
    this.routes = routes;
  }

  public RouteDetails200Response polylines(@jakarta.annotation.Nonnull List<RoutePolyline> polylines) {
    
    this.polylines = polylines;
    return this;
  }

  public RouteDetails200Response addPolylinesItem(RoutePolyline polylinesItem) {
    if (this.polylines == null) {
      this.polylines = new ArrayList<>();
    }
    this.polylines.add(polylinesItem);
    return this;
  }

  /**
   * Get polylines
   * @return polylines
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POLYLINES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RoutePolyline> getPolylines() {
    return polylines;
  }


  @JsonProperty(value = JSON_PROPERTY_POLYLINES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolylines(@jakarta.annotation.Nonnull List<RoutePolyline> polylines) {
    this.polylines = polylines;
  }

  public RouteDetails200Response stops(@jakarta.annotation.Nonnull List<Place> stops) {
    
    this.stops = stops;
    return this;
  }

  public RouteDetails200Response addStopsItem(Place stopsItem) {
    if (this.stops == null) {
      this.stops = new ArrayList<>();
    }
    this.stops.add(stopsItem);
    return this;
  }

  /**
   * Get stops
   * @return stops
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STOPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Place> getStops() {
    return stops;
  }


  @JsonProperty(value = JSON_PROPERTY_STOPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStops(@jakarta.annotation.Nonnull List<Place> stops) {
    this.stops = stops;
  }

  public RouteDetails200Response zoomFiltered(@jakarta.annotation.Nonnull Boolean zoomFiltered) {
    
    this.zoomFiltered = zoomFiltered;
    return this;
  }

  /**
   * Always false for this endpoint.
   * @return zoomFiltered
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ZOOM_FILTERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getZoomFiltered() {
    return zoomFiltered;
  }


  @JsonProperty(value = JSON_PROPERTY_ZOOM_FILTERED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setZoomFiltered(@jakarta.annotation.Nonnull Boolean zoomFiltered) {
    this.zoomFiltered = zoomFiltered;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteDetails200Response routeDetails200Response = (RouteDetails200Response) o;
    return Objects.equals(this.routes, routeDetails200Response.routes) &&
        Objects.equals(this.polylines, routeDetails200Response.polylines) &&
        Objects.equals(this.stops, routeDetails200Response.stops) &&
        Objects.equals(this.zoomFiltered, routeDetails200Response.zoomFiltered);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routes, polylines, stops, zoomFiltered);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteDetails200Response {\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("    polylines: ").append(toIndentedString(polylines)).append("\n");
    sb.append("    stops: ").append(toIndentedString(stops)).append("\n");
    sb.append("    zoomFiltered: ").append(toIndentedString(zoomFiltered)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

