/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RouteColor
 */
@JsonPropertyOrder({
  RouteColor.JSON_PROPERTY_COLOR,
  RouteColor.JSON_PROPERTY_TEXT_COLOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class RouteColor {
  public static final String JSON_PROPERTY_COLOR = "color";
  @jakarta.annotation.Nonnull
  private String color;

  public static final String JSON_PROPERTY_TEXT_COLOR = "textColor";
  @jakarta.annotation.Nonnull
  private String textColor;

  public RouteColor() {
  }

  public RouteColor color(@jakarta.annotation.Nonnull String color) {
    
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COLOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getColor() {
    return color;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColor(@jakarta.annotation.Nonnull String color) {
    this.color = color;
  }

  public RouteColor textColor(@jakarta.annotation.Nonnull String textColor) {
    
    this.textColor = textColor;
    return this;
  }

  /**
   * Get textColor
   * @return textColor
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEXT_COLOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTextColor() {
    return textColor;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT_COLOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTextColor(@jakarta.annotation.Nonnull String textColor) {
    this.textColor = textColor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteColor routeColor = (RouteColor) o;
    return Objects.equals(this.color, routeColor.color) &&
        Objects.equals(this.textColor, routeColor.textColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, textColor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteColor {\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    textColor: ").append(toIndentedString(textColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

