/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServerConfig
 */
@JsonPropertyOrder({
  ServerConfig.JSON_PROPERTY_HAS_ELEVATION,
  ServerConfig.JSON_PROPERTY_HAS_ROUTED_TRANSFERS,
  ServerConfig.JSON_PROPERTY_HAS_STREET_ROUTING,
  ServerConfig.JSON_PROPERTY_MAX_ONE_TO_ALL_TRAVEL_TIME_LIMIT,
  ServerConfig.JSON_PROPERTY_MAX_PRE_POST_TRANSIT_TIME_LIMIT,
  ServerConfig.JSON_PROPERTY_MAX_DIRECT_TIME_LIMIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class ServerConfig {
  public static final String JSON_PROPERTY_HAS_ELEVATION = "hasElevation";
  @jakarta.annotation.Nonnull
  private Boolean hasElevation;

  public static final String JSON_PROPERTY_HAS_ROUTED_TRANSFERS = "hasRoutedTransfers";
  @jakarta.annotation.Nonnull
  private Boolean hasRoutedTransfers;

  public static final String JSON_PROPERTY_HAS_STREET_ROUTING = "hasStreetRouting";
  @jakarta.annotation.Nonnull
  private Boolean hasStreetRouting;

  public static final String JSON_PROPERTY_MAX_ONE_TO_ALL_TRAVEL_TIME_LIMIT = "maxOneToAllTravelTimeLimit";
  @jakarta.annotation.Nullable
  private BigDecimal maxOneToAllTravelTimeLimit;

  public static final String JSON_PROPERTY_MAX_PRE_POST_TRANSIT_TIME_LIMIT = "maxPrePostTransitTimeLimit";
  @jakarta.annotation.Nonnull
  private BigDecimal maxPrePostTransitTimeLimit;

  public static final String JSON_PROPERTY_MAX_DIRECT_TIME_LIMIT = "maxDirectTimeLimit";
  @jakarta.annotation.Nonnull
  private BigDecimal maxDirectTimeLimit;

  public ServerConfig() {
  }

  public ServerConfig hasElevation(@jakarta.annotation.Nonnull Boolean hasElevation) {
    
    this.hasElevation = hasElevation;
    return this;
  }

  /**
   * true if elevation is loaded
   * @return hasElevation
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_ELEVATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getHasElevation() {
    return hasElevation;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_ELEVATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasElevation(@jakarta.annotation.Nonnull Boolean hasElevation) {
    this.hasElevation = hasElevation;
  }

  public ServerConfig hasRoutedTransfers(@jakarta.annotation.Nonnull Boolean hasRoutedTransfers) {
    
    this.hasRoutedTransfers = hasRoutedTransfers;
    return this;
  }

  /**
   * true if routed transfers available
   * @return hasRoutedTransfers
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_ROUTED_TRANSFERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getHasRoutedTransfers() {
    return hasRoutedTransfers;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_ROUTED_TRANSFERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasRoutedTransfers(@jakarta.annotation.Nonnull Boolean hasRoutedTransfers) {
    this.hasRoutedTransfers = hasRoutedTransfers;
  }

  public ServerConfig hasStreetRouting(@jakarta.annotation.Nonnull Boolean hasStreetRouting) {
    
    this.hasStreetRouting = hasStreetRouting;
    return this;
  }

  /**
   * true if street routing is available
   * @return hasStreetRouting
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HAS_STREET_ROUTING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getHasStreetRouting() {
    return hasStreetRouting;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_STREET_ROUTING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHasStreetRouting(@jakarta.annotation.Nonnull Boolean hasStreetRouting) {
    this.hasStreetRouting = hasStreetRouting;
  }

  public ServerConfig maxOneToAllTravelTimeLimit(@jakarta.annotation.Nullable BigDecimal maxOneToAllTravelTimeLimit) {
    
    this.maxOneToAllTravelTimeLimit = maxOneToAllTravelTimeLimit;
    return this;
  }

  /**
   * limit for maxTravelTime API param in minutes
   * @return maxOneToAllTravelTimeLimit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_ONE_TO_ALL_TRAVEL_TIME_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getMaxOneToAllTravelTimeLimit() {
    return maxOneToAllTravelTimeLimit;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_ONE_TO_ALL_TRAVEL_TIME_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxOneToAllTravelTimeLimit(@jakarta.annotation.Nullable BigDecimal maxOneToAllTravelTimeLimit) {
    this.maxOneToAllTravelTimeLimit = maxOneToAllTravelTimeLimit;
  }

  public ServerConfig maxPrePostTransitTimeLimit(@jakarta.annotation.Nonnull BigDecimal maxPrePostTransitTimeLimit) {
    
    this.maxPrePostTransitTimeLimit = maxPrePostTransitTimeLimit;
    return this;
  }

  /**
   * limit for maxPrePostTransitTime API param in seconds
   * @return maxPrePostTransitTimeLimit
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAX_PRE_POST_TRANSIT_TIME_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getMaxPrePostTransitTimeLimit() {
    return maxPrePostTransitTimeLimit;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_PRE_POST_TRANSIT_TIME_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxPrePostTransitTimeLimit(@jakarta.annotation.Nonnull BigDecimal maxPrePostTransitTimeLimit) {
    this.maxPrePostTransitTimeLimit = maxPrePostTransitTimeLimit;
  }

  public ServerConfig maxDirectTimeLimit(@jakarta.annotation.Nonnull BigDecimal maxDirectTimeLimit) {
    
    this.maxDirectTimeLimit = maxDirectTimeLimit;
    return this;
  }

  /**
   * limit for maxDirectTime API param in seconds
   * @return maxDirectTimeLimit
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAX_DIRECT_TIME_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getMaxDirectTimeLimit() {
    return maxDirectTimeLimit;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_DIRECT_TIME_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxDirectTimeLimit(@jakarta.annotation.Nonnull BigDecimal maxDirectTimeLimit) {
    this.maxDirectTimeLimit = maxDirectTimeLimit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerConfig serverConfig = (ServerConfig) o;
    return Objects.equals(this.hasElevation, serverConfig.hasElevation) &&
        Objects.equals(this.hasRoutedTransfers, serverConfig.hasRoutedTransfers) &&
        Objects.equals(this.hasStreetRouting, serverConfig.hasStreetRouting) &&
        Objects.equals(this.maxOneToAllTravelTimeLimit, serverConfig.maxOneToAllTravelTimeLimit) &&
        Objects.equals(this.maxPrePostTransitTimeLimit, serverConfig.maxPrePostTransitTimeLimit) &&
        Objects.equals(this.maxDirectTimeLimit, serverConfig.maxDirectTimeLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hasElevation, hasRoutedTransfers, hasStreetRouting, maxOneToAllTravelTimeLimit, maxPrePostTransitTimeLimit, maxDirectTimeLimit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerConfig {\n");
    sb.append("    hasElevation: ").append(toIndentedString(hasElevation)).append("\n");
    sb.append("    hasRoutedTransfers: ").append(toIndentedString(hasRoutedTransfers)).append("\n");
    sb.append("    hasStreetRouting: ").append(toIndentedString(hasStreetRouting)).append("\n");
    sb.append("    maxOneToAllTravelTimeLimit: ").append(toIndentedString(maxOneToAllTravelTimeLimit)).append("\n");
    sb.append("    maxPrePostTransitTimeLimit: ").append(toIndentedString(maxPrePostTransitTimeLimit)).append("\n");
    sb.append("    maxDirectTimeLimit: ").append(toIndentedString(maxDirectTimeLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

