/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Place;
import dev.bileto.motis.client.model.Route;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StopInfo200Response
 */
@JsonPropertyOrder({
  StopInfo200Response.JSON_PROPERTY_PLACE,
  StopInfo200Response.JSON_PROPERTY_ROUTES
})
@JsonTypeName("stopInfo_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class StopInfo200Response {
  public static final String JSON_PROPERTY_PLACE = "place";
  @jakarta.annotation.Nonnull
  private Place place;

  public static final String JSON_PROPERTY_ROUTES = "routes";
  @jakarta.annotation.Nonnull
  private List<Route> routes = new ArrayList<>();

  public StopInfo200Response() {
  }

  public StopInfo200Response place(@jakarta.annotation.Nonnull Place place) {
    
    this.place = place;
    return this;
  }

  /**
   * metadata of the requested stop
   * @return place
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PLACE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Place getPlace() {
    return place;
  }


  @JsonProperty(value = JSON_PROPERTY_PLACE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlace(@jakarta.annotation.Nonnull Place place) {
    this.place = place;
  }

  public StopInfo200Response routes(@jakarta.annotation.Nonnull List<Route> routes) {
    
    this.routes = routes;
    return this;
  }

  public StopInfo200Response addRoutesItem(Route routesItem) {
    if (this.routes == null) {
      this.routes = new ArrayList<>();
    }
    this.routes.add(routesItem);
    return this;
  }

  /**
   * list of routes serving the stop(s)
   * @return routes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Route> getRoutes() {
    return routes;
  }


  @JsonProperty(value = JSON_PROPERTY_ROUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoutes(@jakarta.annotation.Nonnull List<Route> routes) {
    this.routes = routes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopInfo200Response stopInfo200Response = (StopInfo200Response) o;
    return Objects.equals(this.place, stopInfo200Response.place) &&
        Objects.equals(this.routes, stopInfo200Response.routes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(place, routes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopInfo200Response {\n");
    sb.append("    place: ").append(toIndentedString(place)).append("\n");
    sb.append("    routes: ").append(toIndentedString(routes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

