/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TransitRouteInfo
 */
@JsonPropertyOrder({
  TransitRouteInfo.JSON_PROPERTY_ID,
  TransitRouteInfo.JSON_PROPERTY_SHORT_NAME,
  TransitRouteInfo.JSON_PROPERTY_LONG_NAME,
  TransitRouteInfo.JSON_PROPERTY_COLOR,
  TransitRouteInfo.JSON_PROPERTY_TEXT_COLOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class TransitRouteInfo {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_SHORT_NAME = "shortName";
  @jakarta.annotation.Nonnull
  private String shortName;

  public static final String JSON_PROPERTY_LONG_NAME = "longName";
  @jakarta.annotation.Nonnull
  private String longName;

  public static final String JSON_PROPERTY_COLOR = "color";
  @jakarta.annotation.Nullable
  private String color;

  public static final String JSON_PROPERTY_TEXT_COLOR = "textColor";
  @jakarta.annotation.Nullable
  private String textColor;

  public TransitRouteInfo() {
  }

  public TransitRouteInfo id(@jakarta.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull String id) {
    this.id = id;
  }

  public TransitRouteInfo shortName(@jakarta.annotation.Nonnull String shortName) {
    
    this.shortName = shortName;
    return this;
  }

  /**
   * Get shortName
   * @return shortName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SHORT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getShortName() {
    return shortName;
  }


  @JsonProperty(value = JSON_PROPERTY_SHORT_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShortName(@jakarta.annotation.Nonnull String shortName) {
    this.shortName = shortName;
  }

  public TransitRouteInfo longName(@jakarta.annotation.Nonnull String longName) {
    
    this.longName = longName;
    return this;
  }

  /**
   * Get longName
   * @return longName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LONG_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLongName() {
    return longName;
  }


  @JsonProperty(value = JSON_PROPERTY_LONG_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLongName(@jakarta.annotation.Nonnull String longName) {
    this.longName = longName;
  }

  public TransitRouteInfo color(@jakarta.annotation.Nullable String color) {
    
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getColor() {
    return color;
  }


  @JsonProperty(value = JSON_PROPERTY_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(@jakarta.annotation.Nullable String color) {
    this.color = color;
  }

  public TransitRouteInfo textColor(@jakarta.annotation.Nullable String textColor) {
    
    this.textColor = textColor;
    return this;
  }

  /**
   * Get textColor
   * @return textColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTextColor() {
    return textColor;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT_COLOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextColor(@jakarta.annotation.Nullable String textColor) {
    this.textColor = textColor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransitRouteInfo transitRouteInfo = (TransitRouteInfo) o;
    return Objects.equals(this.id, transitRouteInfo.id) &&
        Objects.equals(this.shortName, transitRouteInfo.shortName) &&
        Objects.equals(this.longName, transitRouteInfo.longName) &&
        Objects.equals(this.color, transitRouteInfo.color) &&
        Objects.equals(this.textColor, transitRouteInfo.textColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, shortName, longName, color, textColor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransitRouteInfo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    longName: ").append(toIndentedString(longName)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    textColor: ").append(toIndentedString(textColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

