/*
 * MOTIS API
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v5
 * Contact: felix@triptix.tech
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.bileto.motis.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.bileto.motis.client.model.Place;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * transfer from one location to another
 */
@JsonPropertyOrder({
  Transfer.JSON_PROPERTY_TO,
  Transfer.JSON_PROPERTY_DEFAULT,
  Transfer.JSON_PROPERTY_FOOT,
  Transfer.JSON_PROPERTY_FOOT_ROUTED,
  Transfer.JSON_PROPERTY_WHEELCHAIR,
  Transfer.JSON_PROPERTY_WHEELCHAIR_ROUTED,
  Transfer.JSON_PROPERTY_WHEELCHAIR_USES_ELEVATOR,
  Transfer.JSON_PROPERTY_CAR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class Transfer {
  public static final String JSON_PROPERTY_TO = "to";
  @jakarta.annotation.Nonnull
  private Place to;

  public static final String JSON_PROPERTY_DEFAULT = "default";
  @jakarta.annotation.Nullable
  private BigDecimal _default;

  public static final String JSON_PROPERTY_FOOT = "foot";
  @jakarta.annotation.Nullable
  private BigDecimal foot;

  public static final String JSON_PROPERTY_FOOT_ROUTED = "footRouted";
  @jakarta.annotation.Nullable
  private BigDecimal footRouted;

  public static final String JSON_PROPERTY_WHEELCHAIR = "wheelchair";
  @jakarta.annotation.Nullable
  private BigDecimal wheelchair;

  public static final String JSON_PROPERTY_WHEELCHAIR_ROUTED = "wheelchairRouted";
  @jakarta.annotation.Nullable
  private BigDecimal wheelchairRouted;

  public static final String JSON_PROPERTY_WHEELCHAIR_USES_ELEVATOR = "wheelchairUsesElevator";
  @jakarta.annotation.Nullable
  private Boolean wheelchairUsesElevator;

  public static final String JSON_PROPERTY_CAR = "car";
  @jakarta.annotation.Nullable
  private BigDecimal car;

  public Transfer() {
  }

  public Transfer to(@jakarta.annotation.Nonnull Place to) {
    
    this.to = to;
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Place getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@jakarta.annotation.Nonnull Place to) {
    this.to = to;
  }

  public Transfer _default(@jakarta.annotation.Nullable BigDecimal _default) {
    
    this._default = _default;
    return this;
  }

  /**
   * optional; missing if the GTFS did not contain a transfer transfer duration in minutes according to GTFS (+heuristics) 
   * @return _default
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDefault() {
    return _default;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefault(@jakarta.annotation.Nullable BigDecimal _default) {
    this._default = _default;
  }

  public Transfer foot(@jakarta.annotation.Nullable BigDecimal foot) {
    
    this.foot = foot;
    return this;
  }

  /**
   * optional; missing if no path was found (timetable / osr) transfer duration in minutes for the foot profile 
   * @return foot
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFoot() {
    return foot;
  }


  @JsonProperty(value = JSON_PROPERTY_FOOT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFoot(@jakarta.annotation.Nullable BigDecimal foot) {
    this.foot = foot;
  }

  public Transfer footRouted(@jakarta.annotation.Nullable BigDecimal footRouted) {
    
    this.footRouted = footRouted;
    return this;
  }

  /**
   * optional; missing if no path was found with foot routing transfer duration in minutes for the foot profile 
   * @return footRouted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOOT_ROUTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getFootRouted() {
    return footRouted;
  }


  @JsonProperty(value = JSON_PROPERTY_FOOT_ROUTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFootRouted(@jakarta.annotation.Nullable BigDecimal footRouted) {
    this.footRouted = footRouted;
  }

  public Transfer wheelchair(@jakarta.annotation.Nullable BigDecimal wheelchair) {
    
    this.wheelchair = wheelchair;
    return this;
  }

  /**
   * optional; missing if no path was found with the wheelchair profile  transfer duration in minutes for the wheelchair profile 
   * @return wheelchair
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WHEELCHAIR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWheelchair() {
    return wheelchair;
  }


  @JsonProperty(value = JSON_PROPERTY_WHEELCHAIR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWheelchair(@jakarta.annotation.Nullable BigDecimal wheelchair) {
    this.wheelchair = wheelchair;
  }

  public Transfer wheelchairRouted(@jakarta.annotation.Nullable BigDecimal wheelchairRouted) {
    
    this.wheelchairRouted = wheelchairRouted;
    return this;
  }

  /**
   * optional; missing if no path was found with the wheelchair profile transfer duration in minutes for the wheelchair profile 
   * @return wheelchairRouted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WHEELCHAIR_ROUTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getWheelchairRouted() {
    return wheelchairRouted;
  }


  @JsonProperty(value = JSON_PROPERTY_WHEELCHAIR_ROUTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWheelchairRouted(@jakarta.annotation.Nullable BigDecimal wheelchairRouted) {
    this.wheelchairRouted = wheelchairRouted;
  }

  public Transfer wheelchairUsesElevator(@jakarta.annotation.Nullable Boolean wheelchairUsesElevator) {
    
    this.wheelchairUsesElevator = wheelchairUsesElevator;
    return this;
  }

  /**
   * optional; missing if no path was found with the wheelchair profile true if the wheelchair path uses an elevator 
   * @return wheelchairUsesElevator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WHEELCHAIR_USES_ELEVATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getWheelchairUsesElevator() {
    return wheelchairUsesElevator;
  }


  @JsonProperty(value = JSON_PROPERTY_WHEELCHAIR_USES_ELEVATOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWheelchairUsesElevator(@jakarta.annotation.Nullable Boolean wheelchairUsesElevator) {
    this.wheelchairUsesElevator = wheelchairUsesElevator;
  }

  public Transfer car(@jakarta.annotation.Nullable BigDecimal car) {
    
    this.car = car;
    return this;
  }

  /**
   * optional; missing if no path was found with car routing transfer duration in minutes for the car profile 
   * @return car
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCar() {
    return car;
  }


  @JsonProperty(value = JSON_PROPERTY_CAR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCar(@jakarta.annotation.Nullable BigDecimal car) {
    this.car = car;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transfer transfer = (Transfer) o;
    return Objects.equals(this.to, transfer.to) &&
        Objects.equals(this._default, transfer._default) &&
        Objects.equals(this.foot, transfer.foot) &&
        Objects.equals(this.footRouted, transfer.footRouted) &&
        Objects.equals(this.wheelchair, transfer.wheelchair) &&
        Objects.equals(this.wheelchairRouted, transfer.wheelchairRouted) &&
        Objects.equals(this.wheelchairUsesElevator, transfer.wheelchairUsesElevator) &&
        Objects.equals(this.car, transfer.car);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, _default, foot, footRouted, wheelchair, wheelchairRouted, wheelchairUsesElevator, car);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transfer {\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    foot: ").append(toIndentedString(foot)).append("\n");
    sb.append("    footRouted: ").append(toIndentedString(footRouted)).append("\n");
    sb.append("    wheelchair: ").append(toIndentedString(wheelchair)).append("\n");
    sb.append("    wheelchairRouted: ").append(toIndentedString(wheelchairRouted)).append("\n");
    sb.append("    wheelchairUsesElevator: ").append(toIndentedString(wheelchairUsesElevator)).append("\n");
    sb.append("    car: ").append(toIndentedString(car)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

